class Seedcities < ActiveRecord::Migration
  def change
  	City.create([
    {:name=>'Port Blair',:latitude=>'11.67',:longitude=>'92.76',:state=>'Andaman and Nicobar Islands'},
    {:name=>'Adilabad',:latitude=>'19.68',:longitude=>'78.53',:state=>'Andhra Pradesh'},
    {:name=>'Adoni',:latitude=>'15.63',:longitude=>'77.28',:state=>'Andhra Pradesh'},
    {:name=>'Alwal',:latitude=>'17.50',:longitude=>'78.54',:state=>'Andhra Pradesh'},
    {:name=>'Anakapalle',:latitude=>'17.69',:longitude=>'83.00',:state=>'Andhra Pradesh'},
    {:name=>'Anantapur',:latitude=>'14.70',:longitude=>'77.59',:state=>'Andhra Pradesh'},
    {:name=>'Bapatla',:latitude=>'15.91',:longitude=>'80.47',:state=>'Andhra Pradesh'},
    {:name=>'Belampalli',:latitude=>'19.06',:longitude=>'79.49',:state=>'Andhra Pradesh'},
    {:name=>'Bhimavaram',:latitude=>'16.55',:longitude=>'81.53',:state=>'Andhra Pradesh'},
    {:name=>'Bhongir',:latitude=>'17.52',:longitude=>'78.88',:state=>'Andhra Pradesh'},
    {:name=>'Bobbili',:latitude=>'18.57',:longitude=>'83.37',:state=>'Andhra Pradesh'},
    {:name=>'Bodhan',:latitude=>'18.66',:longitude=>'77.88',:state=>'Andhra Pradesh'},
    {:name=>'Chilakalurupet',:latitude=>'16.10',:longitude=>'80.16',:state=>'Andhra Pradesh'},
    {:name=>'Chinna Chawk',:latitude=>'14.47',:longitude=>'78.83',:state=>'Andhra Pradesh'},
    {:name=>'Chirala',:latitude=>'15.84',:longitude=>'80.35',:state=>'Andhra Pradesh'},
    {:name=>'Chittur',:latitude=>'13.22',:longitude=>'79.10',:state=>'Andhra Pradesh'},
    {:name=>'Cuddapah',:latitude=>'14.48',:longitude=>'78.81',:state=>'Andhra Pradesh'},
    {:name=>'Dharmavaram',:latitude=>'14.42',:longitude=>'77.71',:state=>'Andhra Pradesh'},
    {:name=>'Dhone',:latitude=>'15.42',:longitude=>'77.88',:state=>'Andhra Pradesh'},
    {:name=>'Eluru',:latitude=>'16.72',:longitude=>'81.11',:state=>'Andhra Pradesh'},
    {:name=>'Gaddiannaram',:latitude=>'17.36',:longitude=>'78.52',:state=>'Andhra Pradesh'},
    {:name=>'Gadwal',:latitude=>'16.23',:longitude=>'77.80',:state=>'Andhra Pradesh'},
    {:name=>'Gajuwaka',:latitude=>'17.70',:longitude=>'83.21',:state=>'Andhra Pradesh'},
    {:name=>'Gudivada',:latitude=>'16.44',:longitude=>'81.00',:state=>'Andhra Pradesh'},
    {:name=>'Gudur',:latitude=>'14.15',:longitude=>'79.84',:state=>'Andhra Pradesh'},
    {:name=>'Guntakal',:latitude=>'15.18',:longitude=>'77.37',:state=>'Andhra Pradesh'},
    {:name=>'Guntur',:latitude=>'16.31',:longitude=>'80.44',:state=>'Andhra Pradesh'},
    {:name=>'Hindupur',:latitude=>'13.83',:longitude=>'77.48',:state=>'Andhra Pradesh'},
    {:name=>'Hyderabad',:latitude=>'17.40',:longitude=>'78.48',:state=>'Andhra Pradesh'},
    {:name=>'Jagtial',:latitude=>'18.80',:longitude=>'78.91',:state=>'Andhra Pradesh'},
    {:name=>'Kadiri',:latitude=>'14.12',:longitude=>'78.16',:state=>'Andhra Pradesh'},
    {:name=>'Kagaznagar',:latitude=>'19.34',:longitude=>'79.48',:state=>'Andhra Pradesh'},
    {:name=>'Kakinada',:latitude=>'16.96',:longitude=>'82.24',:state=>'Andhra Pradesh'},
    {:name=>'Kallur',:latitude=>'15.69',:longitude=>'77.77',:state=>'Andhra Pradesh'},
    {:name=>'Kamareddi',:latitude=>'18.32',:longitude=>'78.35',:state=>'Andhra Pradesh'},
    {:name=>'Kapra',:latitude=>'17.37',:longitude=>'78.48',:state=>'Andhra Pradesh'},
    {:name=>'Karimnagar',:latitude=>'18.45',:longitude=>'79.13',:state=>'Andhra Pradesh'},
    {:name=>'Karnul',:latitude=>'15.83',:longitude=>'78.03',:state=>'Andhra Pradesh'},
    {:name=>'Kavali',:latitude=>'14.92',:longitude=>'79.99',:state=>'Andhra Pradesh'},
    {:name=>'Khammam',:latitude=>'17.25',:longitude=>'80.15',:state=>'Andhra Pradesh'},
    {:name=>'Kodar',:latitude=>'16.98',:longitude=>'79.97',:state=>'Andhra Pradesh'},
    {:name=>'Kondukur',:latitude=>'15.22',:longitude=>'79.91',:state=>'Andhra Pradesh'},
    {:name=>'Koratla',:latitude=>'18.82',:longitude=>'78.72',:state=>'Andhra Pradesh'},
    {:name=>'Kottagudem',:latitude=>'17.56',:longitude=>'80.64',:state=>'Andhra Pradesh'},
    {:name=>'Kukatpalle',:latitude=>'17.49',:longitude=>'78.41',:state=>'Andhra Pradesh'},
    {:name=>'Lalbahadur Nagar',:latitude=>'17.43',:longitude=>'78.50',:state=>'Andhra Pradesh'},
    {:name=>'Machilipatnam',:latitude=>'16.19',:longitude=>'81.14',:state=>'Andhra Pradesh'},
    {:name=>'Mahbubnagar',:latitude=>'16.74',:longitude=>'77.98',:state=>'Andhra Pradesh'},
    {:name=>'Malkajgiri',:latitude=>'17.55',:longitude=>'78.59',:state=>'Andhra Pradesh'},
    {:name=>'Mancheral',:latitude=>'18.88',:longitude=>'79.45',:state=>'Andhra Pradesh'},
    {:name=>'Mandamarri',:latitude=>'18.97',:longitude=>'79.47',:state=>'Andhra Pradesh'},
    {:name=>'Mangalagiri',:latitude=>'16.44',:longitude=>'80.56',:state=>'Andhra Pradesh'},
    {:name=>'Markapur',:latitude=>'15.73',:longitude=>'79.28',:state=>'Andhra Pradesh'},
    {:name=>'Miryalaguda',:latitude=>'16.87',:longitude=>'79.57',:state=>'Andhra Pradesh'},
    {:name=>'Nalgonda',:latitude=>'17.06',:longitude=>'79.26',:state=>'Andhra Pradesh'},
    {:name=>'Nandyal',:latitude=>'15.49',:longitude=>'78.48',:state=>'Andhra Pradesh'},
    {:name=>'Narasapur',:latitude=>'16.45',:longitude=>'81.70',:state=>'Andhra Pradesh'},
    {:name=>'Narasaraopet',:latitude=>'16.24',:longitude=>'80.04',:state=>'Andhra Pradesh'},
    {:name=>'Nellur',:latitude=>'14.46',:longitude=>'79.98',:state=>'Andhra Pradesh'},
    {:name=>'Nirmal',:latitude=>'19.12',:longitude=>'78.35',:state=>'Andhra Pradesh'},
    {:name=>'Nizamabad',:latitude=>'18.68',:longitude=>'78.10',:state=>'Andhra Pradesh'},
    {:name=>'Nuzvid',:latitude=>'16.78',:longitude=>'80.85',:state=>'Andhra Pradesh'},
    {:name=>'Ongole',:latitude=>'15.50',:longitude=>'80.05',:state=>'Andhra Pradesh'},
    {:name=>'Palakollu',:latitude=>'16.52',:longitude=>'81.75',:state=>'Andhra Pradesh'},
    {:name=>'Palasa',:latitude=>'18.77',:longitude=>'84.42',:state=>'Andhra Pradesh'},
    {:name=>'Palwancha',:latitude=>'17.60',:longitude=>'80.68',:state=>'Andhra Pradesh'},
    {:name=>'Patancheru',:latitude=>'17.53',:longitude=>'78.27',:state=>'Andhra Pradesh'},
    {:name=>'Piduguralla',:latitude=>'16.48',:longitude=>'79.90',:state=>'Andhra Pradesh'},
    {:name=>'Ponnur',:latitude=>'16.07',:longitude=>'80.56',:state=>'Andhra Pradesh'},
    {:name=>'Proddatur',:latitude=>'14.73',:longitude=>'78.55',:state=>'Andhra Pradesh'},
    {:name=>'Qutubullapur',:latitude=>'17.43',:longitude=>'78.47',:state=>'Andhra Pradesh'},
    {:name=>'Rajamahendri',:latitude=>'17.02',:longitude=>'81.79',:state=>'Andhra Pradesh'},
    {:name=>'Rajampet',:latitude=>'14.18',:longitude=>'79.17',:state=>'Andhra Pradesh'},
    {:name=>'Rajendranagar',:latitude=>'17.29',:longitude=>'78.39',:state=>'Andhra Pradesh'},
    {:name=>'Ramachandrapuram',:latitude=>'17.56',:longitude=>'78.04',:state=>'Andhra Pradesh'},
    {:name=>'Ramagundam',:latitude=>'18.80',:longitude=>'79.45',:state=>'Andhra Pradesh'},
    {:name=>'Rayachoti',:latitude=>'14.05',:longitude=>'78.75',:state=>'Andhra Pradesh'},
    {:name=>'Rayadrug',:latitude=>'14.70',:longitude=>'76.87',:state=>'Andhra Pradesh'},
    {:name=>'Samalkot',:latitude=>'17.06',:longitude=>'82.18',:state=>'Andhra Pradesh'},
    {:name=>'Sangareddi',:latitude=>'17.63',:longitude=>'78.08',:state=>'Andhra Pradesh'},
    {:name=>'Sattenapalle',:latitude=>'16.40',:longitude=>'80.18',:state=>'Andhra Pradesh'},
    {:name=>'Serilungampalle',:latitude=>'17.48',:longitude=>'78.33',:state=>'Andhra Pradesh'},
    {:name=>'Siddipet',:latitude=>'18.11',:longitude=>'78.84',:state=>'Andhra Pradesh'},
    {:name=>'Sikandarabad',:latitude=>'17.47',:longitude=>'78.52',:state=>'Andhra Pradesh'},
    {:name=>'Sirsilla',:latitude=>'18.40',:longitude=>'78.81',:state=>'Andhra Pradesh'},
    {:name=>'Srikakulam',:latitude=>'18.30',:longitude=>'83.90',:state=>'Andhra Pradesh'},
    {:name=>'Srikalahasti',:latitude=>'13.76',:longitude=>'79.70',:state=>'Andhra Pradesh'},
    {:name=>'Suriapet',:latitude=>'17.15',:longitude=>'79.62',:state=>'Andhra Pradesh'},
    {:name=>'Tadepalle',:latitude=>'16.48',:longitude=>'80.60',:state=>'Andhra Pradesh'},
    {:name=>'Tadepallegudem',:latitude=>'16.82',:longitude=>'81.52',:state=>'Andhra Pradesh'},
    {:name=>'Tadpatri',:latitude=>'14.91',:longitude=>'78.00',:state=>'Andhra Pradesh'},
    {:name=>'Tandur',:latitude=>'17.25',:longitude=>'77.58',:state=>'Andhra Pradesh'},
    {:name=>'Tanuku',:latitude=>'16.75',:longitude=>'81.69',:state=>'Andhra Pradesh'},
    {:name=>'Tenali',:latitude=>'16.24',:longitude=>'80.65',:state=>'Andhra Pradesh'},
    {:name=>'Tirupati',:latitude=>'13.63',:longitude=>'79.41',:state=>'Andhra Pradesh'},
    {:name=>'Tuni',:latitude=>'17.35',:longitude=>'82.55',:state=>'Andhra Pradesh'},
    {:name=>'Uppal Kalan',:latitude=>'17.38',:longitude=>'78.55',:state=>'Andhra Pradesh'},
    {:name=>'Vijayawada',:latitude=>'16.52',:longitude=>'80.63',:state=>'Andhra Pradesh'},
    {:name=>'Vinukonda',:latitude=>'16.05',:longitude=>'79.75',:state=>'Andhra Pradesh'},
    {:name=>'Visakhapatnam',:latitude=>'17.73',:longitude=>'83.30',:state=>'Andhra Pradesh'},
    {:name=>'Vizianagaram',:latitude=>'18.12',:longitude=>'83.40',:state=>'Andhra Pradesh'},
    {:name=>'Vuyyuru',:latitude=>'16.37',:longitude=>'80.85',:state=>'Andhra Pradesh'},
    {:name=>'Wanparti',:latitude=>'16.37',:longitude=>'78.07',:state=>'Andhra Pradesh'},
    {:name=>'Warangal',:latitude=>'18.01',:longitude=>'79.58',:state=>'Andhra Pradesh'},
    {:name=>'Yemmiganur',:latitude=>'15.73',:longitude=>'77.48',:state=>'Andhra Pradesh'},
    {:name=>'Itanagar',:latitude=>'27.14',:longitude=>'93.61',:state=>'Arunachal Pradesh'},
    {:name=>'Barpeta',:latitude=>'26.32',:longitude=>'91.00',:state=>'Assam'},
    {:name=>'Bongaigaon',:latitude=>'26.48',:longitude=>'90.54',:state=>'Assam'},
    {:name=>'Dhuburi',:latitude=>'26.03',:longitude=>'89.97',:state=>'Assam'},
    {:name=>'Dibrugarh',:latitude=>'27.49',:longitude=>'94.91',:state=>'Assam'},
    {:name=>'Diphu',:latitude=>'25.84',:longitude=>'93.43',:state=>'Assam'},
    {:name=>'Guwahati',:latitude=>'26.19',:longitude=>'91.75',:state=>'Assam'},
    {:name=>'Jorhat',:latitude=>'26.76',:longitude=>'94.20',:state=>'Assam'},
    {:name=>'Karimganj',:latitude=>'24.85',:longitude=>'92.36',:state=>'Assam'},
    {:name=>'Visakhapatnam',:latitude=>'17.73',:longitude=>'83.30',:state=>'Andhra Pradesh'},
    {:name=>'Lakhimpur',:latitude=>'27.24',:longitude=>'94.10',:state=>'Assam'},
    {:name=>'Lanka',:latitude=>'25.93',:longitude=>'92.95',:state=>'Assam'},
    {:name=>'Nagaon',:latitude=>'26.35',:longitude=>'92.68',:state=>'Assam'},
    {:name=>'Sibsagar',:latitude=>'26.99',:longitude=>'94.63',:state=>'Assam'},
    {:name=>'Silchar',:latitude=>'24.83',:longitude=>'92.77',:state=>'Assam'},
    {:name=>'Tezpur',:latitude=>'26.63',:longitude=>'92.79',:state=>'Assam'},
    {:name=>'Tinsukia',:latitude=>'27.50',:longitude=>'95.36',:state=>'Assam'},
    {:name=>'Alipur Duar',:latitude=>'26.50',:longitude=>'89.53',:state=>'West Bengal'},
    {:name=>'Arambagh',:latitude=>'22.88',:longitude=>'87.78',:state=>'West Bengal'},
    {:name=>'Asansol',:latitude=>'23.69',:longitude=>'86.98',:state=>'West Bengal'},
    {:name=>'Ashoknagar Kalyangarh',:latitude=>'22.84',:longitude=>'88.63',:state=>'West Bengal'},
    {:name=>'Baharampur',:latitude=>'24.10',:longitude=>'88.24',:state=>'West Bengal'},
    {:name=>'Baidyabati',:latitude=>'22.79',:longitude=>'88.33',:state=>'West Bengal'},
    {:name=>'Baj Baj',:latitude=>'22.48',:longitude=>'88.17',:state=>'West Bengal'},
    {:name=>'Bally',:latitude=>'22.65',:longitude=>'88.35',:state=>'West Bengal'},
    {:name=>'Bally Cantonment',:latitude=>'22.65',:longitude=>'88.36',:state=>'West Bengal'},
    {:name=>'Balurghat',:latitude=>'25.23',:longitude=>'88.77',:state=>'West Bengal'},
    {:name=>'Bangaon',:latitude=>'23.05',:longitude=>'88.83',:state=>'West Bengal'},
    {:name=>'Bankra',:latitude=>'22.58',:longitude=>'88.31',:state=>'West Bengal'},
    {:name=>'Bankura',:latitude=>'23.24',:longitude=>'87.07',:state=>'West Bengal'},
    {:name=>'Bansbaria',:latitude=>'22.95',:longitude=>'88.40',:state=>'West Bengal'},
    {:name=>'Baranagar',:latitude=>'22.64',:longitude=>'88.37',:state=>'West Bengal'},
    {:name=>'Barddhaman',:latitude=>'23.24',:longitude=>'87.86',:state=>'West Bengal'},
    {:name=>'Basirhat',:latitude=>'22.66',:longitude=>'88.86',:state=>'West Bengal'},
    {:name=>'Bhadreswar',:latitude=>'22.84',:longitude=>'88.35',:state=>'West Bengal'},
    {:name=>'Bhatpara',:latitude=>'22.89',:longitude=>'88.42',:state=>'West Bengal'},
    {:name=>'Bidhannagar',:latitude=>'22.57',:longitude=>'88.42',:state=>'West Bengal'},
    {:name=>'Binnaguri',:latitude=>'26.74',:longitude=>'89.037',:state=>'West Bengal'},
    {:name=>'Bishnupur',:latitude=>'23.08',:longitude=>'87.33',:state=>'West Bengal'},
    {:name=>'Bolpur',:latitude=>'23.67',:longitude=>'87.70',:state=>'West Bengal'},
    {:name=>'Kolkata',:latitude=>'22.57',:longitude=>'88.36',:state=>'West Bengal'},
    {:name=>'Chakdaha',:latitude=>'22.48',:longitude=>'88.35',:state=>'West Bengal'},
    {:name=>'Champdani',:latitude=>'22.81',:longitude=>'88.34',:state=>'West Bengal'},
    {:name=>'Chandannagar',:latitude=>'22.89',:longitude=>'88.37',:state=>'West Bengal'},
    {:name=>'Contai',:latitude=>'21.79',:longitude=>'87.75',:state=>'West Bengal'},
    {:name=>'Dabgram',:latitude=>'',:longitude=>'',:state=>'West Bengal'},
    {:name=>'Darjiling',:latitude=>'27.05',:longitude=>'88.26',:state=>'West Bengal'},
    {:name=>'Dhulian',:latitude=>'24.68',:longitude=>'87.97',:state=>'West Bengal'},
    {:name=>'Dinhata',:latitude=>'26.13',:longitude=>'89.47',:state=>'West Bengal'},
    {:name=>'Dum Dum',:latitude=>'22.63',:longitude=>'88.42',:state=>'West Bengal'},
    {:name=>'Durgapur',:latitude=>'23.50',:longitude=>'87.31',:state=>'West Bengal'},
    {:name=>'Gangarampur',:latitude=>'25.40',:longitude=>'88.52',:state=>'West Bengal'},
    {:name=>'Garulia',:latitude=>'22.83',:longitude=>'88.37',:state=>'West Bengal'},
    {:name=>'Gayespur',:latitude=>'22.98',:longitude=>'88.51',:state=>'West Bengal'},
    {:name=>'Ghatal',:latitude=>'22.67',:longitude=>'87.72',:state=>'West Bengal'},
    {:name=>'Gopalpur',:latitude=>'',:longitude=>'',:state=>'West Bengal'},
    {:name=>'Habra',:latitude=>'22.84',:longitude=>'88.62',:state=>'West Bengal'},
    {:name=>'Halisahar',:latitude=>'22.95',:longitude=>'88.42',:state=>'West Bengal'},
    {:name=>'Haora',:latitude=>'22.58',:longitude=>'88.33',:state=>'West Bengal'},
    {:name=>'HugliChunchura',:latitude=>'22.91',:longitude=>'88.40',:state=>'West Bengal'},
    {:name=>'Ingraj Bazar',:latitude=>'25.01',:longitude=>'88.14',:state=>'West Bengal'},
    {:name=>'Islampur',:latitude=>'26.27',:longitude=>'88.20',:state=>'West Bengal'},
    {:name=>'Jalpaiguri',:latitude=>'26.53',:longitude=>'88.71',:state=>'West Bengal'},
    {:name=>'Jamuria',:latitude=>'23.70',:longitude=>'87.08',:state=>'West Bengal'},
    {:name=>'Jangipur',:latitude=>'24.47',:longitude=>'88.07',:state=>'West Bengal'},
    {:name=>'Jhargram',:latitude=>'22.45',:longitude=>'86.98',:state=>'West Bengal'},
    {:name=>'Kaliyaganj',:latitude=>'25.63',:longitude=>'88.32',:state=>'West Bengal'},
    {:name=>'Kalna',:latitude=>'23.22',:longitude=>'88.37',:state=>'West Bengal'},
    {:name=>'Kalyani',:latitude=>'22.98',:longitude=>'88.48',:state=>'West Bengal'},
    {:name=>'Kamarhati',:latitude=>'22.67',:longitude=>'88.37',:state=>'West Bengal'},
    {:name=>'Kanchrapara',:latitude=>'22.95',:longitude=>'88.45',:state=>'West Bengal'},
    {:name=>'Kandi',:latitude=>'23.95',:longitude=>'88.03',:state=>'West Bengal'},
    {:name=>'Karsiyang',:latitude=>'26.88',:longitude=>'88.28',:state=>'West Bengal'},
    {:name=>'Katwa',:latitude=>'23.65',:longitude=>'88.13',:state=>'West Bengal'},
    {:name=>'Kharagpur',:latitude=>'22.34',:longitude=>'87.31',:state=>'West Bengal'},
    {:name=>'Kharagpur Railway Settlement',:latitude=>'22.34',:longitude=>'87.26',:state=>'West Bengal'},
    {:name=>'Khardaha',:latitude=>'22.73',:longitude=>'88.38',:state=>'West Bengal'},
    {:name=>'Kharia',:latitude=>'',:longitude=>'',:state=>'West Bengal'},
    {:name=>'Koch Bihar',:latitude=>'26.33',:longitude=>'89.46',:state=>'West Bengal'},
    {:name=>'Konnagar',:latitude=>'22.70',:longitude=>'88.36',:state=>'West Bengal'},
    {:name=>'Krishnanagar',:latitude=>'23.41',:longitude=>'88.51',:state=>'West Bengal'},
    {:name=>'Kulti',:latitude=>'23.72',:longitude=>'86.89',:state=>'West Bengal'},
    {:name=>'Madhyamgram',:latitude=>'22.70',:longitude=>'88.45',:state=>'West Bengal'},
    {:name=>'Maheshtala',:latitude=>'22.51',:longitude=>'88.23',:state=>'West Bengal'},
    {:name=>'Memari',:latitude=>'23.20',:longitude=>'88.12',:state=>'West Bengal'},
    {:name=>'Midnapur',:latitude=>'22.33',:longitude=>'87.15',:state=>'West Bengal'},
    {:name=>'Naihati',:latitude=>'22.91',:longitude=>'88.43',:state=>'West Bengal'},
    {:name=>'Navadwip',:latitude=>'23.42',:longitude=>'88.37',:state=>'West Bengal'},
    {:name=>'Ni Barakpur',:latitude=>'22.77',:longitude=>'88.36',:state=>'West Bengal'},
    {:name=>'North Barakpur',:latitude=>'22.78',:longitude=>'88.37',:state=>'West Bengal'},
    {:name=>'North Dum Dum',:latitude=>'22.64',:longitude=>'88.41',:state=>'West Bengal'},
    {:name=>'Old Maldah',:latitude=>'',:longitude=>'',:state=>'West Bengal'},
    {:name=>'Panihati',:latitude=>'22.69',:longitude=>'88.37',:state=>'West Bengal'},
    {:name=>'Phulia',:latitude=>'23.24',:longitude=>'88.50',:state=>'West Bengal'},
    {:name=>'Pujali',:latitude=>'22.47',:longitude=>'88.15',:state=>'West Bengal'},
    {:name=>'Puruliya',:latitude=>'23.34',:longitude=>'86.36',:state=>'West Bengal'},
    {:name=>'Raiganj',:latitude=>'25.62',:longitude=>'88.12',:state=>'West Bengal'},
    {:name=>'Rajpur',:latitude=>'22.44',:longitude=>'88.44',:state=>'West Bengal'},
    {:name=>'Rampur Hat',:latitude=>'24.17',:longitude=>'87.78',:state=>'West Bengal'},
    {:name=>'Ranaghat',:latitude=>'23.19',:longitude=>'88.58',:state=>'West Bengal'},
    {:name=>'Raniganj',:latitude=>'23.62',:longitude=>'87.11',:state=>'West Bengal'},
    {:name=>'Rishra',:latitude=>'22.71',:longitude=>'88.36',:state=>'West Bengal'},
    {:name=>'Shantipur',:latitude=>'23.26',:longitude=>'88.44',:state=>'West Bengal'},
    {:name=>'Shiliguri',:latitude=>'26.73',:longitude=>'88.42',:state=>'West Bengal'},
    {:name=>'Shrirampur',:latitude=>'22.74',:longitude=>'88.35',:state=>'West Bengal'},
    {:name=>'Siuri',:latitude=>'23.91',:longitude=>'87.53',:state=>'West Bengal'},
    {:name=>'South Dum Dum',:latitude=>'22.61',:longitude=>'88.41',:state=>'West Bengal'},
    {:name=>'Titagarh',:latitude=>'22.74',:longitude=>'88.38',:state=>'West Bengal'},
    {:name=>'Ulubaria',:latitude=>'22.47',:longitude=>'88.11',:state=>'West Bengal'},
    {:name=>'UttarparaKotrung',:latitude=>'22.66',:longitude=>'88.35',:state=>'West Bengal'},
    {:name=>'Araria',:latitude=>'26.15',:longitude=>'87.52',:state=>'Bihar'},
    {:name=>'Arrah',:latitude=>'25.56',:longitude=>'84.66',:state=>'Bihar'},
    {:name=>'Aurangabad',:latitude=>'24.75',:longitude=>'84.37',:state=>'Bihar'},
    {:name=>'Bagaha',:latitude=>'27.10',:longitude=>'84.09',:state=>'Bihar'},
    {:name=>'Begusarai',:latitude=>'25.42',:longitude=>'86.12',:state=>'Bihar'},
    {:name=>'Bettiah',:latitude=>'26.81',:longitude=>'84.50',:state=>'Bihar'},
    {:name=>'Bhabua',:latitude=>'25.05',:longitude=>'83.62',:state=>'Bihar'},
    {:name=>'Bhagalpur',:latitude=>'25.26',:longitude=>'86.98',:state=>'Bihar'},
    {:name=>'Bihar',:latitude=>'25.21',:longitude=>'85.52',:state=>'Bihar'},
    {:name=>'Buxar',:latitude=>'25.58',:longitude=>'83.98',:state=>'Bihar'},
    {:name=>'Chhapra',:latitude=>'25.78',:longitude=>'84.72',:state=>'Bihar'},
    {:name=>'Darbhanga',:latitude=>'26.16',:longitude=>'85.88',:state=>'Bihar'},
    {:name=>'Dehri',:latitude=>'24.91',:longitude=>'84.18',:state=>'Bihar'},
    {:name=>'DighaMainpura',:latitude=>'',:longitude=>'',:state=>'Bihar'},
    {:name=>'Dinapur',:latitude=>'25.64',:longitude=>'85.04',:state=>'Bihar'},
    {:name=>'Dumraon',:latitude=>'25.55',:longitude=>'84.15',:state=>'Bihar'},
    {:name=>'Gaya',:latitude=>'24.81',:longitude=>'85.00',:state=>'Bihar'},
    {:name=>'Gopalganj',:latitude=>'26.47',:longitude=>'84.43',:state=>'Bihar'},
    {:name=>'Goura',:latitude=>'',:longitude=>'',:state=>'Bihar'},
    {:name=>'Hajipur',:latitude=>'',:longitude=>'',:state=>'Bihar'},
    {:name=>'Jahanabad',:latitude=>'25.22',:longitude=>'84.98',:state=>'Bihar'},
    {:name=>'Jamalpur',:latitude=>'25.32',:longitude=>'86.48',:state=>'Bihar'},
    {:name=>'Jamui',:latitude=>'24.92',:longitude=>'86.22',:state=>'Bihar'},
    {:name=>'Katihar',:latitude=>'25.55',:longitude=>'87.57',:state=>'Bihar'},
    {:name=>'Khagaria',:latitude=>'25.50',:longitude=>'86.48',:state=>'Bihar'},
    {:name=>'Khagaul',:latitude=>'25.58',:longitude=>'85.05',:state=>'Bihar'},
    {:name=>'Kishanganj',:latitude=>'26.11',:longitude=>'87.95',:state=>'Bihar'},
    {:name=>'Lakhisarai',:latitude=>'25.18',:longitude=>'86.09',:state=>'Bihar'},
    {:name=>'Madhipura',:latitude=>'25.92',:longitude=>'86.78',:state=>'Bihar'},
    {:name=>'Madhubani',:latitude=>'26.37',:longitude=>'86.06',:state=>'Bihar'},
    {:name=>'Masaurhi',:latitude=>'25.35',:longitude=>'85.03',:state=>'Bihar'},
    {:name=>'Mokama',:latitude=>'25.40',:longitude=>'85.92',:state=>'Bihar'},
    {:name=>'Motihari',:latitude=>'26.66',:longitude=>'84.91',:state=>'Bihar'},
    {:name=>'Munger',:latitude=>'25.39',:longitude=>'86.47',:state=>'Bihar'},
    {:name=>'Muzaffarpur',:latitude=>'26.13',:longitude=>'85.38',:state=>'Bihar'},
    {:name=>'Nawada',:latitude=>'24.88',:longitude=>'85.54',:state=>'Bihar'},
    {:name=>'Patna',:latitude=>'25.62',:longitude=>'85.13',:state=>'Bihar'},
    {:name=>'Phulwari',:latitude=>'25.60',:longitude=>'85.13',:state=>'Bihar'},
    {:name=>'Purnia',:latitude=>'25.78',:longitude=>'87.47',:state=>'Bihar'},
    {:name=>'Raxaul',:latitude=>'26.98',:longitude=>'84.85',:state=>'Bihar'},
    {:name=>'Saharsa',:latitude=>'25.88',:longitude=>'86.59',:state=>'Bihar'},
    {:name=>'Samastipur',:latitude=>'25.85',:longitude=>'85.78',:state=>'Bihar'},
    {:name=>'Sasaram',:latitude=>'24.96',:longitude=>'84.01',:state=>'Bihar'},
    {:name=>'Sitamarhi',:latitude=>'26.61',:longitude=>'85.48',:state=>'Bihar'},
    {:name=>'Siwan',:latitude=>'26.23',:longitude=>'84.35',:state=>'Bihar'},
    {:name=>'Supaul',:latitude=>'26.12',:longitude=>'86.60',:state=>'Bihar'},
    {:name=>'Chandigarh',:latitude=>'30.75',:longitude=>'76.78',:state=>'Chandigarh'},
    {:name=>'Ambikapur',:latitude=>'23.13',:longitude=>'83.20',:state=>'Chhattisgarh'},
    {:name=>'Bhilai',:latitude=>'21.21',:longitude=>'81.38',:state=>'Chhattisgarh'},
    {:name=>'Bilaspur',:latitude=>'22.09',:longitude=>'82.15',:state=>'Chhattisgarh'},
    {:name=>'Charoda',:latitude=>'21.23',:longitude=>'81.50',:state=>'Chhattisgarh'},
    {:name=>'Chirmiri',:latitude=>'23.21',:longitude=>'82.41',:state=>'Chhattisgarh'},
    {:name=>'Dhamtari',:latitude=>'20.71',:longitude=>'81.55',:state=>'Chhattisgarh'},
    {:name=>'Durg',:latitude=>'21.20',:longitude=>'81.28',:state=>'Chhattisgarh'},
    {:name=>'Jagdalpur',:latitude=>'19.09',:longitude=>'82.03',:state=>'Chhattisgarh'},
    {:name=>'Korba',:latitude=>'22.35',:longitude=>'82.69',:state=>'Chhattisgarh'},
    {:name=>'Raigarh',:latitude=>'21.90',:longitude=>'83.39',:state=>'Chhattisgarh'},
    {:name=>'Raipur',:latitude=>'21.24',:longitude=>'81.63',:state=>'Chhattisgarh'},
    {:name=>'Rajnandgaon',:latitude=>'21.10',:longitude=>'81.04',:state=>'Chhattisgarh'},
    {:name=>'Bhalswa Jahangirpur',:latitude=>'28.74',:longitude=>'77.17',:state=>'Delhi'},
    {:name=>'Burari',:latitude=>'',:longitude=>'',:state=>'Delhi'},
    {:name=>'Chilla Saroda Bangar',:latitude=>'',:longitude=>'',:state=>'Delhi'},
    {:name=>'Dallo Pura',:latitude=>'',:longitude=>'',:state=>'Delhi'},
    {:name=>'Delhi',:latitude=>'28.67',:longitude=>'77.21',:state=>'Delhi'},
    {:name=>'Deoli',:latitude=>'28.49',:longitude=>'77.22',:state=>'Delhi'},
    {:name=>'Dilli Cantonment',:latitude=>'28.57',:longitude=>'77.16',:state=>'Delhi'},
    {:name=>'New Delhi',:latitude=>'28.57',:longitude=>'77.16',:state=>'Delhi'},
    {:name=>'Gokalpur',:latitude=>'28.71',:longitude=>'77.28',:state=>'Delhi'},
    {:name=>'Hastsal',:latitude=>'',:longitude=>'',:state=>'Delhi'},
    {:name=>'Jaffrabad',:latitude=>'',:longitude=>'',:state=>'Delhi'},
    {:name=>'Karawal Nagar',:latitude=>'',:longitude=>'',:state=>'Delhi'},
    {:name=>'Khajuri Khas',:latitude=>'',:longitude=>'',:state=>'Delhi'},
    {:name=>'Kirari Suleman Nagar',:latitude=>'',:longitude=>'',:state=>'Delhi'},
    {:name=>'Mandoli',:latitude=>'',:longitude=>'',:state=>'Delhi'},
    {:name=>'Mithe Pur',:latitude=>'',:longitude=>'',:state=>'Delhi'},
    {:name=>'Molarband',:latitude=>'',:longitude=>'',:state=>'Delhi'},
    {:name=>'Mundka',:latitude=>'',:longitude=>'',:state=>'Delhi'},
    {:name=>'Mustafabad',:latitude=>'',:longitude=>'',:state=>'Delhi'},
    {:name=>'Nangloi Jat',:latitude=>'28.68',:longitude=>'77.07',:state=>'Delhi'},
    {:name=>'Ni Dilli',:latitude=>'28.60',:longitude=>'77.22',:state=>'Delhi'},
    {:name=>'Pul Pehlad',:latitude=>'',:longitude=>'',:state=>'Delhi'},
    {:name=>'Puth Kalan',:latitude=>'',:longitude=>'',:state=>'Delhi'},
    {:name=>'Roshan Pura',:latitude=>'28.60',:longitude=>'76.99',:state=>'Delhi'},
    {:name=>'Sadat Pur Gujran',:latitude=>'',:longitude=>'',:state=>'Delhi'},
    {:name=>'Sultanpur Majra',:latitude=>'28.76',:longitude=>'77.06',:state=>'Delhi'},
    {:name=>'Tajpul',:latitude=>'',:longitude=>'',:state=>'Delhi'},
    {:name=>'Tigri',:latitude=>'28.50',:longitude=>'77.22',:state=>'Delhi'},
    {:name=>'Ziauddin Pur',:latitude=>'',:longitude=>'',:state=>'Delhi'},
    {:name=>'Madgaon',:latitude=>'15.28',:longitude=>'73.94',:state=>'Goa'},
    {:name=>'Mormugao',:latitude=>'15.42',:longitude=>'73.78',:state=>'Goa'},
    {:name=>'Panaji',:latitude=>'15.50',:longitude=>'73.81',:state=>'Goa'},
    {:name=>'Goa',:latitude=>'15.50',:longitude=>'73.81',:state=>'Goa'},
    {:name=>'Ahmedabad',:latitude=>'23.03',:longitude=>'72.58',:state=>'Gujarat'},
    {:name=>'Amreli',:latitude=>'21.61',:longitude=>'71.22',:state=>'Gujarat'},
    {:name=>'Anand',:latitude=>'22.56',:longitude=>'72.95',:state=>'Gujarat'},
    {:name=>'Anjar',:latitude=>'23.12',:longitude=>'70.02',:state=>'Gujarat'},
    {:name=>'Bardoli',:latitude=>'21.12',:longitude=>'73.12',:state=>'Gujarat'},
    {:name=>'Bharuch',:latitude=>'21.71',:longitude=>'72.97',:state=>'Gujarat'},
    {:name=>'Bhavnagar',:latitude=>'21.79',:longitude=>'72.13',:state=>'Gujarat'},
    {:name=>'Bhuj',:latitude=>'23.26',:longitude=>'69.66',:state=>'Gujarat'},
    {:name=>'Borsad',:latitude=>'22.42',:longitude=>'72.90',:state=>'Gujarat'},
    {:name=>'Botad',:latitude=>'22.18',:longitude=>'71.66',:state=>'Gujarat'},
    {:name=>'Chandkheda',:latitude=>'23.15',:longitude=>'72.61',:state=>'Gujarat'},
    {:name=>'Chandlodiya',:latitude=>'23.10',:longitude=>'72.56',:state=>'Gujarat'},
    {:name=>'Dabhoi',:latitude=>'22.13',:longitude=>'73.41',:state=>'Gujarat'},
    {:name=>'Dahod',:latitude=>'22.84',:longitude=>'74.25',:state=>'Gujarat'},
    {:name=>'Dholka',:latitude=>'22.74',:longitude=>'72.44',:state=>'Gujarat'},
    {:name=>'Dhoraji',:latitude=>'21.74',:longitude=>'70.44',:state=>'Gujarat'},
    {:name=>'Dhrangadhra',:latitude=>'23.00',:longitude=>'71.46',:state=>'Gujarat'},
    {:name=>'Disa',:latitude=>'24.26',:longitude=>'72.18',:state=>'Gujarat'},
    {:name=>'Gandhidham',:latitude=>'23.07',:longitude=>'70.13',:state=>'Gujarat'},
    {:name=>'Gandhinagar',:latitude=>'23.30',:longitude=>'72.63',:state=>'Gujarat'},
    {:name=>'Ghatlodiya',:latitude=>'23.05',:longitude=>'72.55',:state=>'Gujarat'},
    {:name=>'Godhra',:latitude=>'22.77',:longitude=>'73.60',:state=>'Gujarat'},
    {:name=>'Gondal',:latitude=>'21.97',:longitude=>'70.80',:state=>'Gujarat'},
    {:name=>'Himatnagar',:latitude=>'23.60',:longitude=>'72.96',:state=>'Gujarat'},
    {:name=>'Jamnagar',:latitude=>'22.47',:longitude=>'70.07',:state=>'Gujarat'},
    {:name=>'Jamnagar',:latitude=>'',:longitude=>'',:state=>'Gujarat'},
    {:name=>'Jetpur',:latitude=>'21.75',:longitude=>'70.61',:state=>'Gujarat'},
    {:name=>'Junagadh',:latitude=>'21.52',:longitude=>'70.45',:state=>'Gujarat'},
    {:name=>'Kalol',:latitude=>'23.25',:longitude=>'72.49',:state=>'Gujarat'},
    {:name=>'Keshod',:latitude=>'21.31',:longitude=>'70.23',:state=>'Gujarat'},
    {:name=>'Khambhat',:latitude=>'22.32',:longitude=>'72.61',:state=>'Gujarat'},
    {:name=>'Kundla',:latitude=>'21.35',:longitude=>'71.30',:state=>'Gujarat'},
    {:name=>'Mahuva',:latitude=>'21.10',:longitude=>'71.75',:state=>'Gujarat'},
    {:name=>'Mangrol',:latitude=>'21.12',:longitude=>'70.12',:state=>'Gujarat'},
    {:name=>'Modasa',:latitude=>'23.47',:longitude=>'73.30',:state=>'Gujarat'},
    {:name=>'Morvi',:latitude=>'22.82',:longitude=>'70.83',:state=>'Gujarat'},
    {:name=>'Nadiad',:latitude=>'22.70',:longitude=>'72.85',:state=>'Gujarat'},
    {:name=>'Navagam Ghed',:latitude=>'',:longitude=>'',:state=>'Gujarat'},
    {:name=>'Navsari',:latitude=>'20.96',:longitude=>'72.92',:state=>'Gujarat'},
    {:name=>'Palitana',:latitude=>'21.52',:longitude=>'71.83',:state=>'Gujarat'},
    {:name=>'Patan',:latitude=>'23.86',:longitude=>'72.11',:state=>'Gujarat'},
    {:name=>'Porbandar',:latitude=>'21.65',:longitude=>'69.60',:state=>'Gujarat'},
    {:name=>'Puna',:latitude=>'',:longitude=>'',:state=>'Gujarat'},
    {:name=>'Rajkot',:latitude=>'22.31',:longitude=>'70.79',:state=>'Gujarat'},
    {:name=>'Ramod',:latitude=>'',:longitude=>'',:state=>'Gujarat'},
    {:name=>'Ranip',:latitude=>'23.03',:longitude=>'72.54',:state=>'Gujarat'},
    {:name=>'Siddhapur',:latitude=>'23.92',:longitude=>'72.37',:state=>'Gujarat'},
    {:name=>'Sihor',:latitude=>'21.70',:longitude=>'71.97',:state=>'Gujarat'},
    {:name=>'Surat',:latitude=>'21.20',:longitude=>'72.82',:state=>'Gujarat'},
    {:name=>'Surendranagar',:latitude=>'22.71',:longitude=>'71.67',:state=>'Gujarat'},
    {:name=>'Thaltej',:latitude=>'',:longitude=>'',:state=>'Gujarat'},
    {:name=>'Una',:latitude=>'20.82',:longitude=>'71.03',:state=>'Gujarat'},
    {:name=>'Unjha',:latitude=>'23.81',:longitude=>'72.38',:state=>'Gujarat'},
    {:name=>'Upleta',:latitude=>'21.75',:longitude=>'70.27',:state=>'Gujarat'},
    {:name=>'Vadodara',:latitude=>'22.31',:longitude=>'73.18',:state=>'Gujarat'},
    {:name=>'Valsad',:latitude=>'20.62',:longitude=>'72.92',:state=>'Gujarat'},
    {:name=>'Vapi',:latitude=>'20.37',:longitude=>'72.90',:state=>'Gujarat'},
    {:name=>'Vastral',:latitude=>'',:longitude=>'',:state=>'Gujarat'},
    {:name=>'Vejalpur',:latitude=>'',:longitude=>'',:state=>'Gujarat'},
    {:name=>'Veraval',:latitude=>'20.92',:longitude=>'70.34',:state=>'Gujarat'},
    {:name=>'Vijalpor',:latitude=>'',:longitude=>'',:state=>'Gujarat'},
    {:name=>'Visnagar',:latitude=>'23.71',:longitude=>'72.54',:state=>'Gujarat'},
    {:name=>'Wadhwan',:latitude=>'22.73',:longitude=>'71.72',:state=>'Gujarat'},
    {:name=>'Ambala',:latitude=>'30.38',:longitude=>'76.77',:state=>'Haryana'},
    {:name=>'Ambala Cantonment',:latitude=>'30.39',:longitude=>'76.86',:state=>'Haryana'},
    {:name=>'Ambala Sadar',:latitude=>'30.35',:longitude=>'76.84',:state=>'Haryana'},
    {:name=>'Bahadurgarh',:latitude=>'28.69',:longitude=>'76.92',:state=>'Haryana'},
    {:name=>'Bhiwani',:latitude=>'28.81',:longitude=>'76.12',:state=>'Haryana'},
    {:name=>'Charkhi Dadri',:latitude=>'28.60',:longitude=>'76.27',:state=>'Haryana'},
    {:name=>'Dabwali',:latitude=>'29.95',:longitude=>'74.73',:state=>'Haryana'},
    {:name=>'Faridabad',:latitude=>'28.38',:longitude=>'77.30',:state=>'Haryana'},
    {:name=>'Gohana',:latitude=>'29.13',:longitude=>'76.70',:state=>'Haryana'},
    {:name=>'Hisar',:latitude=>'29.17',:longitude=>'75.72',:state=>'Haryana'},
    {:name=>'Jagadhri',:latitude=>'30.18',:longitude=>'77.29',:state=>'Haryana'},
    {:name=>'Jind',:latitude=>'29.31',:longitude=>'76.30',:state=>'Haryana'},
    {:name=>'Kaithal',:latitude=>'29.81',:longitude=>'76.40',:state=>'Haryana'},
    {:name=>'Karnal',:latitude=>'29.69',:longitude=>'76.97',:state=>'Haryana'},
    {:name=>'Narnaul',:latitude=>'28.04',:longitude=>'76.10',:state=>'Haryana'},
    {:name=>'Narwana',:latitude=>'29.62',:longitude=>'76.12',:state=>'Haryana'},
    {:name=>'Palwal',:latitude=>'28.15',:longitude=>'77.32',:state=>'Haryana'},
    {:name=>'Panchkula',:latitude=>'30.70',:longitude=>'76.88',:state=>'Haryana'},
    {:name=>'Panipat',:latitude=>'29.39',:longitude=>'76.96',:state=>'Haryana'},
    {:name=>'Rewari',:latitude=>'28.19',:longitude=>'76.60',:state=>'Haryana'},
    {:name=>'Rohtak',:latitude=>'28.90',:longitude=>'76.58',:state=>'Haryana'},
    {:name=>'Sirsa',:latitude=>'29.53',:longitude=>'75.03',:state=>'Haryana'},
    {:name=>'Sonipat',:latitude=>'28.99',:longitude=>'77.01',:state=>'Haryana'},
    {:name=>'Thanesar',:latitude=>'29.98',:longitude=>'76.82',:state=>'Haryana'},
    {:name=>'Tohana',:latitude=>'29.70',:longitude=>'75.90',:state=>'Haryana'},
    {:name=>'Yamunanagar',:latitude=>'30.14',:longitude=>'77.28',:state=>'Haryana'},
    {:name=>'Shimla',:latitude=>'31.11',:longitude=>'77.16',:state=>'Himachal Pradesh'},
    {:name=>'Anantnag',:latitude=>'33.73',:longitude=>'75.15',:state=>'Jammu and Kashmir'},
    {:name=>'Baramula',:latitude=>'34.20',:longitude=>'74.35',:state=>'Jammu and Kashmir'},
    {:name=>'Bari Brahmana',:latitude=>'',:longitude=>'',:state=>'Jammu and Kashmir'},
    {:name=>'Jammu',:latitude=>'32.71',:longitude=>'74.85',:state=>'Jammu and Kashmir'},
    {:name=>'Kathua',:latitude=>'32.37',:longitude=>'75.52',:state=>'Jammu and Kashmir'},
    {:name=>'Sopur',:latitude=>'34.30',:longitude=>'74.47',:state=>'Jammu and Kashmir'},
    {:name=>'Srinagar',:latitude=>'34.09',:longitude=>'74.79',:state=>'Jammu and Kashmir'},
    {:name=>'Udhampur',:latitude=>'32.93',:longitude=>'75.13',:state=>'Jammu and Kashmir'},
    {:name=>'Adityapur',:latitude=>'22.80',:longitude=>'86.04',:state=>'Jharkhand'},
    {:name=>'Bagbahra',:latitude=>'22.82',:longitude=>'86.20',:state=>'Jharkhand'},
    {:name=>'Bhuli',:latitude=>'23.79',:longitude=>'86.38',:state=>'Jharkhand'},
    {:name=>'Bokaro',:latitude=>'23.78',:longitude=>'85.96',:state=>'Jharkhand'},
    {:name=>'Chaibasa',:latitude=>'22.56',:longitude=>'85.80',:state=>'Jharkhand'},
    {:name=>'Chas',:latitude=>'23.65',:longitude=>'86.17',:state=>'Jharkhand'},
    {:name=>'Daltenganj',:latitude=>'24.05',:longitude=>'84.06',:state=>'Jharkhand'},
    {:name=>'Devghar',:latitude=>'24.49',:longitude=>'86.69',:state=>'Jharkhand'},
    {:name=>'Dhanbad',:latitude=>'23.80',:longitude=>'86.42',:state=>'Jharkhand'},
    {:name=>'Hazaribag',:latitude=>'24.01',:longitude=>'85.36',:state=>'Jharkhand'},
    {:name=>'Jamshedpur',:latitude=>'22.79',:longitude=>'86.20',:state=>'Jharkhand'},
    {:name=>'Jharia',:latitude=>'23.76',:longitude=>'86.42',:state=>'Jharkhand'},
    {:name=>'Jhumri Tilaiya',:latitude=>'24.43',:longitude=>'85.52',:state=>'Jharkhand'},
    {:name=>'Jorapokhar',:latitude=>'23.79',:longitude=>'86.36',:state=>'Jharkhand'},
    {:name=>'Katras',:latitude=>'23.80',:longitude=>'86.28',:state=>'Jharkhand'},
    {:name=>'Lohardaga',:latitude=>'23.43',:longitude=>'84.68',:state=>'Jharkhand'},
    {:name=>'Mango',:latitude=>'22.85',:longitude=>'86.21',:state=>'Jharkhand'},
    {:name=>'Phusro',:latitude=>'23.68',:longitude=>'85.86',:state=>'Jharkhand'},
    {:name=>'Ramgarh',:latitude=>'23.63',:longitude=>'85.51',:state=>'Jharkhand'},
    {:name=>'Ranchi',:latitude=>'23.36',:longitude=>'85.33',:state=>'Jharkhand'},
    {:name=>'Sahibganj',:latitude=>'25.25',:longitude=>'87.62',:state=>'Jharkhand'},
    {:name=>'Saunda',:latitude=>'23.64',:longitude=>'85.37',:state=>'Jharkhand'},
    {:name=>'Sindari',:latitude=>'23.68',:longitude=>'86.49',:state=>'Jharkhand'},
    {:name=>'Bagalkot',:latitude=>'16.19',:longitude=>'75.69',:state=>'Karnataka'},
    {:name=>'Bangalore',:latitude=>'12.97',:longitude=>'77.56',:state=>'Karnataka'},
    {:name=>'Basavakalyan',:latitude=>'17.87',:longitude=>'76.95',:state=>'Karnataka'},
    {:name=>'Belgaum',:latitude=>'15.86',:longitude=>'74.50',:state=>'Karnataka'},
    {:name=>'Bellary',:latitude=>'15.14',:longitude=>'76.91',:state=>'Karnataka'},
    {:name=>'Bhadravati',:latitude=>'13.84',:longitude=>'7a.69',:state=>'Karnataka'},
    {:name=>'Bidar',:latitude=>'17.92',:longitude=>'77.52',:state=>'Karnataka'},
    {:name=>'Bijapur',:latitude=>'16.83',:longitude=>'75.71',:state=>'Karnataka'},
    {:name=>'Bommanahalli',:latitude=>'13.01',:longitude=>'77.63',:state=>'Karnataka'},
    {:name=>'Byatarayanapura',:latitude=>'',:longitude=>'',:state=>'Karnataka'},
    {:name=>'Challakere',:latitude=>'14.32',:longitude=>'76.65',:state=>'Karnataka'},
    {:name=>'Chamrajnagar',:latitude=>'11.92',:longitude=>'76.95',:state=>'Karnataka'},
    {:name=>'Channapatna',:latitude=>'12.66',:longitude=>'77.19',:state=>'Karnataka'},
    {:name=>'Chik Ballapur',:latitude=>'13.47',:longitude=>'77.73',:state=>'Karnataka'},
    {:name=>'Chikmagalur',:latitude=>'13.32',:longitude=>'75.76',:state=>'Karnataka'},
    {:name=>'Chintamani',:latitude=>'13.40',:longitude=>'78.05',:state=>'Karnataka'},
    {:name=>'Chitradurga',:latitude=>'14.23',:longitude=>'76.39',:state=>'Karnataka'},
    {:name=>'Dasarahalli',:latitude=>'13.01',:longitude=>'77.49',:state=>'Karnataka'},
    {:name=>'Davanagere',:latitude=>'14.46',:longitude=>'75.92',:state=>'Karnataka'},
    {:name=>'Dod Ballapur',:latitude=>'13.30',:longitude=>'77.52',:state=>'Karnataka'},
    {:name=>'Gadag',:latitude=>'15.44',:longitude=>'75.63',:state=>'Karnataka'},
    {:name=>'Gangawati',:latitude=>'15.44',:longitude=>'76.52',:state=>'Karnataka'},
    {:name=>'Gokak',:latitude=>'16.18',:longitude=>'74.81',:state=>'Karnataka'},
    {:name=>'Gulbarga',:latitude=>'17.34',:longitude=>'76.82',:state=>'Karnataka'},
    {:name=>'Harihar',:latitude=>'14.52',:longitude=>'75.80',:state=>'Karnataka'},
    {:name=>'Hassan',:latitude=>'13.01',:longitude=>'76.08',:state=>'Karnataka'},
    {:name=>'Haveri',:latitude=>'14.80',:longitude=>'75.40',:state=>'Karnataka'},
    {:name=>'Hiriyur',:latitude=>'13.97',:longitude=>'76.60',:state=>'Karnataka'},
    {:name=>'Hosakote',:latitude=>'',:longitude=>'',:state=>'Karnataka'},
    {:name=>'Hospet',:latitude=>'15.28',:longitude=>'76.37',:state=>'Karnataka'},
    {:name=>'Hubli',:latitude=>'15.36',:longitude=>'75.13',:state=>'Karnataka'},
    {:name=>'Ilkal',:latitude=>'15.97',:longitude=>'76.13',:state=>'Karnataka'},
    {:name=>'Jamkhandi',:latitude=>'16.51',:longitude=>'75.28',:state=>'Karnataka'},
    {:name=>'Kanakapura',:latitude=>'12.54',:longitude=>'77.42',:state=>'Karnataka'},
    {:name=>'Karwar',:latitude=>'14.82',:longitude=>'74.12',:state=>'Karnataka'},
    {:name=>'Kolar',:latitude=>'13.14',:longitude=>'78.13',:state=>'Karnataka'},
    {:name=>'Kollegal',:latitude=>'12.15',:longitude=>'77.12',:state=>'Karnataka'},
    {:name=>'Koppal',:latitude=>'15.35',:longitude=>'76.15',:state=>'Karnataka'},
    {:name=>'Krishnarajapura',:latitude=>'12.97',:longitude=>'77.74',:state=>'Karnataka'},
    {:name=>'Mahadevapura',:latitude=>'',:longitude=>'',:state=>'Karnataka'},
    {:name=>'Maisuru',:latitude=>'12.31',:longitude=>'76.65',:state=>'Karnataka'},
    {:name=>'Mandya',:latitude=>'12.54',:longitude=>'76.89',:state=>'Karnataka'},
    {:name=>'Mangaluru',:latitude=>'12.88',:longitude=>'74.84',:state=>'Karnataka'},
    {:name=>'Nipani',:latitude=>'16.41',:longitude=>'74.38',:state=>'Karnataka'},
    {:name=>'Pattanagere',:latitude=>'',:longitude=>'',:state=>'Karnataka'},
    {:name=>'Puttur',:latitude=>'12.77',:longitude=>'75.22',:state=>'Karnataka'},
    {:name=>'Rabkavi',:latitude=>'16.47',:longitude=>'75.11',:state=>'Karnataka'},
    {:name=>'Raichur',:latitude=>'16.21',:longitude=>'77.35',:state=>'Karnataka'},
    {:name=>'Ramanagaram',:latitude=>'12.72',:longitude=>'77.27',:state=>'Karnataka'},
    {:name=>'Ranibennur',:latitude=>'14.62',:longitude=>'75.61',:state=>'Karnataka'},
    {:name=>'Robertsonpet',:latitude=>'12.97',:longitude=>'78.28',:state=>'Karnataka'},
    {:name=>'Sagar',:latitude=>'14.17',:longitude=>'75.03',:state=>'Karnataka'},
    {:name=>'Shahabad',:latitude=>'17.13',:longitude=>'76.93',:state=>'Karnataka'},
    {:name=>'Shahpur',:latitude=>'16.70',:longitude=>'76.83',:state=>'Karnataka'},
    {:name=>'Shimoga',:latitude=>'13.93',:longitude=>'75.57',:state=>'Karnataka'},
    {:name=>'Shorapur',:latitude=>'16.52',:longitude=>'76.75',:state=>'Karnataka'},
    {:name=>'Sidlaghatta',:latitude=>'13.38',:longitude=>'77.87',:state=>'Karnataka'},
    {:name=>'Sira',:latitude=>'13.75',:longitude=>'76.90',:state=>'Karnataka'},
    {:name=>'Sirsi',:latitude=>'14.62',:longitude=>'74.85',:state=>'Karnataka'},
    {:name=>'Tiptur',:latitude=>'13.27',:longitude=>'76.48',:state=>'Karnataka'},
    {:name=>'Tumkur',:latitude=>'13.34',:longitude=>'77.10',:state=>'Karnataka'},
    {:name=>'Udupi',:latitude=>'13.35',:longitude=>'74.75',:state=>'Karnataka'},
    {:name=>'Ullal',:latitude=>'12.80',:longitude=>'74.85',:state=>'Karnataka'},
    {:name=>'Yadgir',:latitude=>'16.77',:longitude=>'77.13',:state=>'Karnataka'},
    {:name=>'Yelahanka',:latitude=>'13.10',:longitude=>'77.60',:state=>'Karnataka'},
    {:name=>'Alappuzha',:latitude=>'9.50',:longitude=>'76.33',:state=>'Kerala'},
    {:name=>'Beypur',:latitude=>'11.18',:longitude=>'75.82',:state=>'Kerala'},
    {:name=>'Cheruvannur',:latitude=>'11.21',:longitude=>'75.84',:state=>'Kerala'},
    {:name=>'Edakkara',:latitude=>'',:longitude=>'',:state=>'Kerala'},
    {:name=>'Edathala',:latitude=>'10.03',:longitude=>'76.32',:state=>'Kerala'},
    {:name=>'Kalamassery',:latitude=>'10.05',:longitude=>'76.27',:state=>'Kerala'},
    {:name=>'Kannan Devan Hills',:latitude=>'',:longitude=>'',:state=>'Kerala'},
    {:name=>'Kannangad',:latitude=>'12.34',:longitude=>'75.09',:state=>'Kerala'},
    {:name=>'Kannur',:latitude=>'11.86',:longitude=>'75.35',:state=>'Kerala'},
    {:name=>'Kayankulam',:latitude=>'9.17',:longitude=>'76.49',:state=>'Kerala'},
    {:name=>'Kochi',:latitude=>'10.02',:longitude=>'76.22',:state=>'Kerala'},
    {:name=>'Kollam',:latitude=>'8.89',:longitude=>'76.58',:state=>'Kerala'},
    {:name=>'Kottayam',:latitude=>'9.60',:longitude=>'76.52',:state=>'Kerala'},
    {:name=>'Koyilandi',:latitude=>'11.43',:longitude=>'75.70',:state=>'Kerala'},
    {:name=>'Kozhikkod',:latitude=>'11.26',:longitude=>'75.78',:state=>'Kerala'},
    {:name=>'Kunnamkulam',:latitude=>'10.65',:longitude=>'76.08',:state=>'Kerala'},
    {:name=>'Malappuram',:latitude=>'11.07',:longitude=>'76.06',:state=>'Kerala'},
    {:name=>'Manjeri',:latitude=>'11.12',:longitude=>'76.11',:state=>'Kerala'},
    {:name=>'Nedumangad',:latitude=>'8.61',:longitude=>'77.00',:state=>'Kerala'},
    {:name=>'Neyyattinkara',:latitude=>'8.40',:longitude=>'77.08',:state=>'Kerala'},
    {:name=>'Palakkad',:latitude=>'10.78',:longitude=>'76.65',:state=>'Kerala'},
    {:name=>'Pallichal',:latitude=>'',:longitude=>'',:state=>'Kerala'},
    {:name=>'Payyannur',:latitude=>'12.10',:longitude=>'75.19',:state=>'Kerala'},
    {:name=>'Ponnani',:latitude=>'10.78',:longitude=>'75.92',:state=>'Kerala'},
    {:name=>'Talipparamba',:latitude=>'12.03',:longitude=>'75.36',:state=>'Kerala'},
    {:name=>'Thalassery',:latitude=>'11.75',:longitude=>'75.49',:state=>'Kerala'},
    {:name=>'Thiruvananthapuram',:latitude=>'8.51',:longitude=>'76.95',:state=>'Kerala'},
    {:name=>'Thrippunithura',:latitude=>'9.94',:longitude=>'76.35',:state=>'Kerala'},
    {:name=>'Thrissur',:latitude=>'10.52',:longitude=>'76.21',:state=>'Kerala'},
    {:name=>'Tirur',:latitude=>'10.91',:longitude=>'75.92',:state=>'Kerala'},
    {:name=>'Tiruvalla',:latitude=>'9.39',:longitude=>'76.57',:state=>'Kerala'},
    {:name=>'Vadakara',:latitude=>'11.61',:longitude=>'75.58',:state=>'Kerala'},
    {:name=>'Ashoknagar',:latitude=>'24.57',:longitude=>'77.72',:state=>'Madhya Pradesh'},
    {:name=>'Balaghat',:latitude=>'21.80',:longitude=>'80.18',:state=>'Madhya Pradesh'},
    {:name=>'Basoda',:latitude=>'23.85',:longitude=>'77.93',:state=>'Madhya Pradesh'},
    {:name=>'Betul',:latitude=>'21.92',:longitude=>'77.90',:state=>'Madhya Pradesh'},
    {:name=>'Bhind',:latitude=>'26.57',:longitude=>'78.77',:state=>'Madhya Pradesh'},
    {:name=>'Bhopal',:latitude=>'23.24',:longitude=>'77.40',:state=>'Madhya Pradesh'},
    {:name=>'BinaEtawa',:latitude=>'24.20',:longitude=>'78.20',:state=>'Madhya Pradesh'},
    {:name=>'Burhanpur',:latitude=>'21.33',:longitude=>'76.22',:state=>'Madhya Pradesh'},
    {:name=>'Chhatarpur',:latitude=>'24.92',:longitude=>'79.58',:state=>'Madhya Pradesh'},
    {:name=>'Chhindwara',:latitude=>'22.07',:longitude=>'78.94',:state=>'Madhya Pradesh'},
    {:name=>'Dabra',:latitude=>'25.90',:longitude=>'78.33',:state=>'Madhya Pradesh'},
    {:name=>'Damoh',:latitude=>'23.85',:longitude=>'79.44',:state=>'Madhya Pradesh'},
    {:name=>'Datia',:latitude=>'25.67',:longitude=>'78.45',:state=>'Madhya Pradesh'},
    {:name=>'Dewas',:latitude=>'22.97',:longitude=>'76.05',:state=>'Madhya Pradesh'},
    {:name=>'Dhar',:latitude=>'22.60',:longitude=>'75.29',:state=>'Madhya Pradesh'},
    {:name=>'Gohad',:latitude=>'26.43',:longitude=>'78.45',:state=>'Madhya Pradesh'},
    {:name=>'Guna',:latitude=>'24.65',:longitude=>'77.30',:state=>'Madhya Pradesh'},
    {:name=>'Gwalior',:latitude=>'26.23',:longitude=>'78.17',:state=>'Madhya Pradesh'},
    {:name=>'Harda',:latitude=>'22.33',:longitude=>'77.11',:state=>'Madhya Pradesh'},
    {:name=>'Hoshangabad',:latitude=>'22.75',:longitude=>'77.71',:state=>'Madhya Pradesh'},
    {:name=>'Indore',:latitude=>'22.72',:longitude=>'75.86',:state=>'Madhya Pradesh'},
    {:name=>'Itarsi',:latitude=>'22.62',:longitude=>'77.76',:state=>'Madhya Pradesh'},
    {:name=>'Jabalpur',:latitude=>'23.17',:longitude=>'79.94',:state=>'Madhya Pradesh'},
    {:name=>'Jabalpur Cantonment',:latitude=>'23.16',:longitude=>'79.95',:state=>'Madhya Pradesh'},
    {:name=>'Jaora',:latitude=>'23.64',:longitude=>'75.11',:state=>'Madhya Pradesh'},
    {:name=>'Khandwa',:latitude=>'21.83',:longitude=>'76.35',:state=>'Madhya Pradesh'},
    {:name=>'Khargone',:latitude=>'21.83',:longitude=>'75.60',:state=>'Madhya Pradesh'},
    {:name=>'Mandidip',:latitude=>'23.10',:longitude=>'77.52',:state=>'Madhya Pradesh'},
    {:name=>'Mandsaur',:latitude=>'24.07',:longitude=>'75.07',:state=>'Madhya Pradesh'},
    {:name=>'Mau',:latitude=>'22.56',:longitude=>'75.75',:state=>'Madhya Pradesh'},
    {:name=>'Morena',:latitude=>'26.51',:longitude=>'77.99',:state=>'Madhya Pradesh'},
    {:name=>'Murwara',:latitude=>'23.85',:longitude=>'80.39',:state=>'Madhya Pradesh'},
    {:name=>'Nagda',:latitude=>'23.46',:longitude=>'75.42',:state=>'Madhya Pradesh'},
    {:name=>'Nimach',:latitude=>'24.47',:longitude=>'74.87',:state=>'Madhya Pradesh'},
    {:name=>'Pithampur',:latitude=>'',:longitude=>'',:state=>'Madhya Pradesh'},
    {:name=>'Raghogarh',:latitude=>'24.45',:longitude=>'77.20',:state=>'Madhya Pradesh'},
    {:name=>'Ratlam',:latitude=>'23.35',:longitude=>'75.03',:state=>'Madhya Pradesh'},
    {:name=>'Rewa',:latitude=>'24.53',:longitude=>'81.29',:state=>'Madhya Pradesh'},
    {:name=>'Sagar',:latitude=>'23.85',:longitude=>'78.75',:state=>'Madhya Pradesh'},
    {:name=>'Sarni',:latitude=>'22.04',:longitude=>'78.27',:state=>'Madhya Pradesh'},
    {:name=>'Satna',:latitude=>'24.58',:longitude=>'80.83',:state=>'Madhya Pradesh'},
    {:name=>'Sehore',:latitude=>'23.20',:longitude=>'77.08',:state=>'Madhya Pradesh'},
    {:name=>'Sendhwa',:latitude=>'21.68',:longitude=>'75.10',:state=>'Madhya Pradesh'},
    {:name=>'Seoni',:latitude=>'22.10',:longitude=>'79.55',:state=>'Madhya Pradesh'},
    {:name=>'Shahdol',:latitude=>'23.30',:longitude=>'81.36',:state=>'Madhya Pradesh'},
    {:name=>'Shajapur',:latitude=>'23.43',:longitude=>'76.27',:state=>'Madhya Pradesh'},
    {:name=>'Sheopur',:latitude=>'25.67',:longitude=>'76.70',:state=>'Madhya Pradesh'},
    {:name=>'Shivapuri',:latitude=>'25.43',:longitude=>'77.65',:state=>'Madhya Pradesh'},
    {:name=>'Sidhi',:latitude=>'24.42',:longitude=>'81.88',:state=>'Madhya Pradesh'},
    {:name=>'Singrauli',:latitude=>'23.84',:longitude=>'82.27',:state=>'Madhya Pradesh'},
    {:name=>'Tikamgarh',:latitude=>'24.74',:longitude=>'78.83',:state=>'Madhya Pradesh'},
    {:name=>'Ujjain',:latitude=>'23.19',:longitude=>'75.78',:state=>'Madhya Pradesh'},
    {:name=>'Vidisha',:latitude=>'23.53',:longitude=>'77.80',:state=>'Madhya Pradesh'},
    {:name=>'Achalpur',:latitude=>'21.26',:longitude=>'77.50',:state=>'Maharashtra'},
    {:name=>'Ahmadnagar',:latitude=>'19.10',:longitude=>'74.74',:state=>'Maharashtra'},
    {:name=>'Akola',:latitude=>'20.71',:longitude=>'77.00',:state=>'Maharashtra'},
    {:name=>'Akot',:latitude=>'21.10',:longitude=>'77.05',:state=>'Maharashtra'},
    {:name=>'Amalner',:latitude=>'21.05',:longitude=>'75.06',:state=>'Maharashtra'},
    {:name=>'Ambajogai',:latitude=>'18.73',:longitude=>'76.38',:state=>'Maharashtra'},
    {:name=>'Amravati',:latitude=>'20.95',:longitude=>'77.76',:state=>'Maharashtra'},
    {:name=>'Anjangaon',:latitude=>'21.16',:longitude=>'77.31',:state=>'Maharashtra'},
    {:name=>'Aurangabad',:latitude=>'19.89',:longitude=>'75.32',:state=>'Maharashtra'},
    {:name=>'Badlapur',:latitude=>'19.15',:longitude=>'73.27',:state=>'Maharashtra'},
    {:name=>'Ballarpur',:latitude=>'19.85',:longitude=>'79.35',:state=>'Maharashtra'},
    {:name=>'Baramati',:latitude=>'18.15',:longitude=>'74.58',:state=>'Maharashtra'},
    {:name=>'Barsi',:latitude=>'18.24',:longitude=>'75.69',:state=>'Maharashtra'},
    {:name=>'Basmat',:latitude=>'19.32',:longitude=>'77.17',:state=>'Maharashtra'},
    {:name=>'Bhadravati',:latitude=>'20.11',:longitude=>'79.12',:state=>'Maharashtra'},
    {:name=>'Bhandara',:latitude=>'21.18',:longitude=>'79.65',:state=>'Maharashtra'},
    {:name=>'Bhiwandi',:latitude=>'19.30',:longitude=>'73.05',:state=>'Maharashtra'},
    {:name=>'Bhusawal',:latitude=>'21.05',:longitude=>'75.78',:state=>'Maharashtra'},
    {:name=>'Bid',:latitude=>'18.99',:longitude=>'75.76',:state=>'Maharashtra'},
    {:name=>'Mumbai',:latitude=>'18.96',:longitude=>'72.82',:state=>'Maharashtra'},
    {:name=>'Buldana',:latitude=>'20.54',:longitude=>'76.18',:state=>'Maharashtra'},
    {:name=>'Chalisgaon',:latitude=>'20.46',:longitude=>'74.99',:state=>'Maharashtra'},
    {:name=>'Chandrapur',:latitude=>'19.96',:longitude=>'79.30',:state=>'Maharashtra'},
    {:name=>'Chikhli',:latitude=>'20.35',:longitude=>'76.25',:state=>'Maharashtra'},
    {:name=>'Chiplun',:latitude=>'17.53',:longitude=>'73.52',:state=>'Maharashtra'},
    {:name=>'Chopda',:latitude=>'21.25',:longitude=>'75.28',:state=>'Maharashtra'},
    {:name=>'Dahanu',:latitude=>'19.97',:longitude=>'72.73',:state=>'Maharashtra'},
    {:name=>'Deolali',:latitude=>'19.95',:longitude=>'73.84',:state=>'Maharashtra'},
    {:name=>'Dhule',:latitude=>'20.90',:longitude=>'74.77',:state=>'Maharashtra'},
    {:name=>'Digdoh',:latitude=>'',:longitude=>'',:state=>'Maharashtra'},
    {:name=>'Diglur',:latitude=>'18.55',:longitude=>'77.60',:state=>'Maharashtra'},
    {:name=>'Gadchiroli',:latitude=>'20.17',:longitude=>'80.00',:state=>'Maharashtra'},
    {:name=>'Gondiya',:latitude=>'21.47',:longitude=>'80.20',:state=>'Maharashtra'},
    {:name=>'Hinganghat',:latitude=>'20.56',:longitude=>'78.83',:state=>'Maharashtra'},
    {:name=>'Hingoli',:latitude=>'19.72',:longitude=>'77.14',:state=>'Maharashtra'},
    {:name=>'Ichalkaranji',:latitude=>'16.69',:longitude=>'74.46',:state=>'Maharashtra'},
    {:name=>'Jalgaon',:latitude=>'21.01',:longitude=>'75.56',:state=>'Maharashtra'},
    {:name=>'Jalna',:latitude=>'19.85',:longitude=>'75.88',:state=>'Maharashtra'},
    {:name=>'Kalyan',:latitude=>'19.25',:longitude=>'73.16',:state=>'Maharashtra'},
    {:name=>'Kamthi',:latitude=>'21.23',:longitude=>'79.20',:state=>'Maharashtra'},
    {:name=>'Karanja',:latitude=>'20.48',:longitude=>'77.48',:state=>'Maharashtra'},
    {:name=>'Khadki',:latitude=>'18.57',:longitude=>'73.83',:state=>'Maharashtra'},
    {:name=>'Khamgaon',:latitude=>'20.70',:longitude=>'76.56',:state=>'Maharashtra'},
    {:name=>'Khopoli',:latitude=>'18.78',:longitude=>'73.33',:state=>'Maharashtra'},
    {:name=>'Kolhapur',:latitude=>'16.70',:longitude=>'74.22',:state=>'Maharashtra'},
    {:name=>'Kopargaon',:latitude=>'19.88',:longitude=>'74.48',:state=>'Maharashtra'},
    {:name=>'Latur',:latitude=>'18.41',:longitude=>'76.58',:state=>'Maharashtra'},
    {:name=>'Lonavale',:latitude=>'18.75',:longitude=>'73.42',:state=>'Maharashtra'},
    {:name=>'Malegaon',:latitude=>'20.56',:longitude=>'74.52',:state=>'Maharashtra'},
    {:name=>'Malkapur',:latitude=>'20.90',:longitude=>'76.19',:state=>'Maharashtra'},
    {:name=>'Manmad',:latitude=>'20.26',:longitude=>'74.43',:state=>'Maharashtra'},
    {:name=>'Mira Bhayandar',:latitude=>'19.29',:longitude=>'72.85',:state=>'Maharashtra'},
    {:name=>'Nagpur',:latitude=>'21.16',:longitude=>'79.08',:state=>'Maharashtra'},
    {:name=>'Nalasopara',:latitude=>'19.43',:longitude=>'72.78',:state=>'Maharashtra'},
    {:name=>'Nanded',:latitude=>'19.17',:longitude=>'77.29',:state=>'Maharashtra'},
    {:name=>'Nandurbar',:latitude=>'21.38',:longitude=>'74.23',:state=>'Maharashtra'},
    {:name=>'Nashik',:latitude=>'20.01',:longitude=>'73.78',:state=>'Maharashtra'},
    {:name=>'Navghar',:latitude=>'19.34',:longitude=>'72.90',:state=>'Maharashtra'},
    {:name=>'Navi Mumbai',:latitude=>'19.11',:longitude=>'73.06',:state=>'Maharashtra'},
    {:name=>'Navi Mumbai',:latitude=>'19.00',:longitude=>'73.10',:state=>'Maharashtra'},
    {:name=>'Osmanabad',:latitude=>'18.17',:longitude=>'76.03',:state=>'Maharashtra'},
    {:name=>'Palghar',:latitude=>'19.68',:longitude=>'72.75',:state=>'Maharashtra'},
    {:name=>'Pandharpur',:latitude=>'17.68',:longitude=>'75.31',:state=>'Maharashtra'},
    {:name=>'Parbhani',:latitude=>'19.27',:longitude=>'76.76',:state=>'Maharashtra'},
    {:name=>'Phaltan',:latitude=>'17.98',:longitude=>'74.43',:state=>'Maharashtra'},
    {:name=>'Pimpri',:latitude=>'18.62',:longitude=>'73.80',:state=>'Maharashtra'},
    {:name=>'Pune',:latitude=>'18.53',:longitude=>'73.84',:state=>'Maharashtra'},
    {:name=>'Pune Cantonment',:latitude=>'18.50',:longitude=>'73.88',:state=>'Maharashtra'},
    {:name=>'Pusad',:latitude=>'19.91',:longitude=>'77.57',:state=>'Maharashtra'},
    {:name=>'Ratnagiri',:latitude=>'17.00',:longitude=>'73.29',:state=>'Maharashtra'},
    {:name=>'SangliMiraj',:latitude=>'16.86',:longitude=>'74.57',:state=>'Maharashtra'},
    {:name=>'Satara',:latitude=>'17.70',:longitude=>'74.00',:state=>'Maharashtra'},
    {:name=>'Shahada',:latitude=>'21.55',:longitude=>'74.47',:state=>'Maharashtra'},
    {:name=>'Shegaon',:latitude=>'20.78',:longitude=>'76.68',:state=>'Maharashtra'},
    {:name=>'Shirpur',:latitude=>'21.35',:longitude=>'74.88',:state=>'Maharashtra'},
    {:name=>'Sholapur',:latitude=>'17.67',:longitude=>'75.89',:state=>'Maharashtra'},
    {:name=>'Shrirampur',:latitude=>'19.63',:longitude=>'74.64',:state=>'Maharashtra'},
    {:name=>'Sillod',:latitude=>'20.30',:longitude=>'75.65',:state=>'Maharashtra'},
    {:name=>'Thana',:latitude=>'19.20',:longitude=>'72.97',:state=>'Maharashtra'},
    {:name=>'Udgir',:latitude=>'18.40',:longitude=>'77.11',:state=>'Maharashtra'},
    {:name=>'Ulhasnagar',:latitude=>'19.23',:longitude=>'73.15',:state=>'Maharashtra'},
    {:name=>'Uran Islampur',:latitude=>'17.05',:longitude=>'74.27',:state=>'Maharashtra'},
    {:name=>'Vasai',:latitude=>'19.36',:longitude=>'72.80',:state=>'Maharashtra'},
    {:name=>'Virar',:latitude=>'19.47',:longitude=>'72.79',:state=>'Maharashtra'},
    {:name=>'Wadi',:latitude=>'',:longitude=>'',:state=>'Maharashtra'},
    {:name=>'Wani',:latitude=>'20.07',:longitude=>'78.95',:state=>'Maharashtra'},
    {:name=>'Wardha',:latitude=>'20.75',:longitude=>'78.60',:state=>'Maharashtra'},
    {:name=>'Warud',:latitude=>'21.47',:longitude=>'78.27',:state=>'Maharashtra'},
    {:name=>'Washim',:latitude=>'20.10',:longitude=>'77.13',:state=>'Maharashtra'},
    {:name=>'Yavatmal',:latitude=>'20.41',:longitude=>'78.13',:state=>'Maharashtra'},
    {:name=>'Imphal',:latitude=>'24.79',:longitude=>'93.94',:state=>'Manipur'},
    {:name=>'Shillong',:latitude=>'25.57',:longitude=>'91.87',:state=>'Meghalaya'},
    {:name=>'Tura',:latitude=>'25.52',:longitude=>'90.22',:state=>'Meghalaya'},
    {:name=>'Aizawl',:latitude=>'23.71',:longitude=>'92.71',:state=>'Mizoram'},
    {:name=>'Lunglei',:latitude=>'22.88',:longitude=>'92.73',:state=>'Mizoram'},
    {:name=>'Dimapur',:latitude=>'25.92',:longitude=>'93.73',:state=>'Nagaland'},
    {:name=>'Kohima',:latitude=>'25.67',:longitude=>'94.11',:state=>'Nagaland'},
    {:name=>'Wokha',:latitude=>'26.10',:longitude=>'94.27',:state=>'Nagaland'},
    {:name=>'Balangir',:latitude=>'20.71',:longitude=>'83.50',:state=>'Orissa'},
    {:name=>'Baleshwar',:latitude=>'21.49',:longitude=>'86.95',:state=>'Orissa'},
    {:name=>'Barbil',:latitude=>'22.12',:longitude=>'85.40',:state=>'Orissa'},
    {:name=>'Bargarh',:latitude=>'21.34',:longitude=>'83.61',:state=>'Orissa'},
    {:name=>'Baripada',:latitude=>'21.95',:longitude=>'86.73',:state=>'Orissa'},
    {:name=>'Bhadrak',:latitude=>'21.06',:longitude=>'86.52',:state=>'Orissa'},
    {:name=>'Bhawanipatna',:latitude=>'19.91',:longitude=>'83.17',:state=>'Orissa'},
    {:name=>'Bhubaneswar',:latitude=>'20.27',:longitude=>'85.84',:state=>'Orissa'},
    {:name=>'Brahmapur',:latitude=>'19.32',:longitude=>'84.80',:state=>'Orissa'},
    {:name=>'Brajrajnagar',:latitude=>'21.82',:longitude=>'83.91',:state=>'Orissa'},
    {:name=>'Dhenkanal',:latitude=>'20.67',:longitude=>'85.60',:state=>'Orissa'},
    {:name=>'Jaypur',:latitude=>'18.86',:longitude=>'82.56',:state=>'Orissa'},
    {:name=>'Jharsuguda',:latitude=>'21.87',:longitude=>'84.01',:state=>'Orissa'},
    {:name=>'Kataka',:latitude=>'20.47',:longitude=>'85.88',:state=>'Orissa'},
    {:name=>'Kendujhar',:latitude=>'21.63',:longitude=>'85.58',:state=>'Orissa'},
    {:name=>'Paradwip',:latitude=>'20.32',:longitude=>'86.62',:state=>'Orissa'},
    {:name=>'Puri',:latitude=>'19.81',:longitude=>'85.83',:state=>'Orissa'},
    {:name=>'Raurkela',:latitude=>'22.24',:longitude=>'84.81',:state=>'Orissa'},
    {:name=>'Raurkela Industrial Township',:latitude=>'',:longitude=>'',:state=>'Orissa'},
    {:name=>'Rayagada',:latitude=>'19.18',:longitude=>'83.41',:state=>'Orissa'},
    {:name=>'Sambalpur',:latitude=>'21.47',:longitude=>'83.97',:state=>'Orissa'},
    {:name=>'Sunabeda',:latitude=>'18.69',:longitude=>'82.86',:state=>'Orissa'},
    {:name=>'Karaikal',:latitude=>'10.93',:longitude=>'79.83',:state=>'Pondicherry'},
    {:name=>'Ozhukarai',:latitude=>'11.94',:longitude=>'79.77',:state=>'Pondicherry'},
    {:name=>'Pondicherry',:latitude=>'11.94',:longitude=>'79.83',:state=>'Pondicherry'},
    {:name=>'Abohar',:latitude=>'30.14',:longitude=>'74.20',:state=>'Punjab'},
    {:name=>'Amritsar',:latitude=>'31.64',:longitude=>'74.87',:state=>'Punjab'},
    {:name=>'Barnala',:latitude=>'30.39',:longitude=>'75.54',:state=>'Punjab'},
    {:name=>'Batala',:latitude=>'31.82',:longitude=>'75.21',:state=>'Punjab'},
    {:name=>'Bathinda',:latitude=>'30.17',:longitude=>'74.97',:state=>'Punjab'},
    {:name=>'Dhuri',:latitude=>'30.37',:longitude=>'75.87',:state=>'Punjab'},
    {:name=>'Faridkot',:latitude=>'30.68',:longitude=>'74.74',:state=>'Punjab'},
    {:name=>'Fazilka',:latitude=>'30.41',:longitude=>'74.02',:state=>'Punjab'},
    {:name=>'Firozpur',:latitude=>'30.92',:longitude=>'74.61',:state=>'Punjab'},
    {:name=>'Firozpur Cantonment',:latitude=>'30.95',:longitude=>'74.60',:state=>'Punjab'},
    {:name=>'Gobindgarh',:latitude=>'30.66',:longitude=>'76.31',:state=>'Punjab'},
    {:name=>'Gurdaspur',:latitude=>'32.04',:longitude=>'75.40',:state=>'Punjab'},
    {:name=>'Hoshiarpur',:latitude=>'31.53',:longitude=>'75.91',:state=>'Punjab'},
    {:name=>'Jagraon',:latitude=>'30.78',:longitude=>'75.48',:state=>'Punjab'},
    {:name=>'Jalandhar',:latitude=>'31.33',:longitude=>'75.57',:state=>'Punjab'},
    {:name=>'Kapurthala',:latitude=>'31.38',:longitude=>'75.38',:state=>'Punjab'},
    {:name=>'Khanna',:latitude=>'30.71',:longitude=>'76.21',:state=>'Punjab'},
    {:name=>'Kot Kapura',:latitude=>'30.59',:longitude=>'74.80',:state=>'Punjab'},
    {:name=>'Ludhiana',:latitude=>'30.91',:longitude=>'75.84',:state=>'Punjab'},
    {:name=>'Malaut',:latitude=>'30.23',:longitude=>'74.48',:state=>'Punjab'},
    {:name=>'Maler Kotla',:latitude=>'30.54',:longitude=>'75.87',:state=>'Punjab'},
    {:name=>'Mansa',:latitude=>'29.98',:longitude=>'75.39',:state=>'Punjab'},
    {:name=>'Moga',:latitude=>'30.82',:longitude=>'75.17',:state=>'Punjab'},
    {:name=>'Mohali',:latitude=>'30.78',:longitude=>'76.69',:state=>'Punjab'},
    {:name=>'Pathankot',:latitude=>'32.27',:longitude=>'75.64',:state=>'Punjab'},
    {:name=>'Patiala',:latitude=>'30.32',:longitude=>'76.39',:state=>'Punjab'},
    {:name=>'Phagwara',:latitude=>'31.22',:longitude=>'75.76',:state=>'Punjab'},
    {:name=>'Rajpura',:latitude=>'30.48',:longitude=>'76.59',:state=>'Punjab'},
    {:name=>'Rupnagar',:latitude=>'30.98',:longitude=>'76.52',:state=>'Punjab'},
    {:name=>'Samana',:latitude=>'30.15',:longitude=>'76.20',:state=>'Punjab'},
    {:name=>'Sangrur',:latitude=>'30.25',:longitude=>'75.84',:state=>'Punjab'},
    {:name=>'Sirhind',:latitude=>'30.65',:longitude=>'76.38',:state=>'Punjab'},
    {:name=>'Sunam',:latitude=>'30.13',:longitude=>'75.80',:state=>'Punjab'},
    {:name=>'Tarn Taran',:latitude=>'31.45',:longitude=>'74.92',:state=>'Punjab'},
    {:name=>'Ajmer',:latitude=>'26.45',:longitude=>'74.64',:state=>'Rajasthan'},
    {:name=>'Alwar',:latitude=>'27.56',:longitude=>'76.60',:state=>'Rajasthan'},
    {:name=>'Balotra',:latitude=>'25.83',:longitude=>'72.23',:state=>'Rajasthan'},
    {:name=>'Banswara',:latitude=>'23.54',:longitude=>'74.44',:state=>'Rajasthan'},
    {:name=>'Baran',:latitude=>'25.10',:longitude=>'76.51',:state=>'Rajasthan'},
    {:name=>'Bari',:latitude=>'26.65',:longitude=>'77.60',:state=>'Rajasthan'},
    {:name=>'Barmer',:latitude=>'25.75',:longitude=>'71.39',:state=>'Rajasthan'},
    {:name=>'Beawar',:latitude=>'26.10',:longitude=>'74.30',:state=>'Rajasthan'},
    {:name=>'Bharatpur',:latitude=>'27.23',:longitude=>'77.49',:state=>'Rajasthan'},
    {:name=>'Bhilwara',:latitude=>'25.35',:longitude=>'74.63',:state=>'Rajasthan'},
    {:name=>'Bhiwadi',:latitude=>'',:longitude=>'',:state=>'Rajasthan'},
    {:name=>'Bikaner',:latitude=>'28.03',:longitude=>'73.32',:state=>'Rajasthan'},
    {:name=>'Bundi',:latitude=>'25.45',:longitude=>'75.63',:state=>'Rajasthan'},
    {:name=>'Chittaurgarh',:latitude=>'24.89',:longitude=>'74.63',:state=>'Rajasthan'},
    {:name=>'Chomun',:latitude=>'27.17',:longitude=>'75.72',:state=>'Rajasthan'},
    {:name=>'Churu',:latitude=>'28.31',:longitude=>'74.96',:state=>'Rajasthan'},
    {:name=>'Daosa',:latitude=>'26.88',:longitude=>'76.33',:state=>'Rajasthan'},
    {:name=>'Dhaulpur',:latitude=>'26.70',:longitude=>'77.87',:state=>'Rajasthan'},
    {:name=>'Didwana',:latitude=>'27.39',:longitude=>'74.57',:state=>'Rajasthan'},
    {:name=>'Fatehpur',:latitude=>'27.99',:longitude=>'74.95',:state=>'Rajasthan'},
    {:name=>'Ganganagar',:latitude=>'29.93',:longitude=>'73.86',:state=>'Rajasthan'},
    {:name=>'Gangapur',:latitude=>'26.47',:longitude=>'76.72',:state=>'Rajasthan'},
    {:name=>'Hanumangarh',:latitude=>'29.62',:longitude=>'74.29',:state=>'Rajasthan'},
    {:name=>'Hindaun',:latitude=>'26.74',:longitude=>'77.02',:state=>'Rajasthan'},
    {:name=>'Jaipur',:latitude=>'26.92',:longitude=>'75.80',:state=>'Rajasthan'},
    {:name=>'Jaisalmer',:latitude=>'26.92',:longitude=>'70.90',:state=>'Rajasthan'},
    {:name=>'Jalor',:latitude=>'25.35',:longitude=>'72.62',:state=>'Rajasthan'},
    {:name=>'Jhalawar',:latitude=>'24.60',:longitude=>'76.15',:state=>'Rajasthan'},
    {:name=>'Jhunjhunun',:latitude=>'28.13',:longitude=>'75.39',:state=>'Rajasthan'},
    {:name=>'Jodhpur',:latitude=>'26.29',:longitude=>'73.02',:state=>'Rajasthan'},
    {:name=>'Karauli',:latitude=>'26.50',:longitude=>'77.02',:state=>'Rajasthan'},
    {:name=>'Kishangarh',:latitude=>'26.58',:longitude=>'74.86',:state=>'Rajasthan'},
    {:name=>'Kota',:latitude=>'25.18',:longitude=>'75.83',:state=>'Rajasthan'},
    {:name=>'Kuchaman',:latitude=>'27.15',:longitude=>'74.85',:state=>'Rajasthan'},
    {:name=>'Ladnun',:latitude=>'27.64',:longitude=>'74.38',:state=>'Rajasthan'},
    {:name=>'Makrana',:latitude=>'27.05',:longitude=>'74.72',:state=>'Rajasthan'},
    {:name=>'Nagaur',:latitude=>'27.21',:longitude=>'73.73',:state=>'Rajasthan'},
    {:name=>'Nawalgarh',:latitude=>'27.85',:longitude=>'75.27',:state=>'Rajasthan'},
    {:name=>'Nimbahera',:latitude=>'24.62',:longitude=>'74.68',:state=>'Rajasthan'},
    {:name=>'Nokha',:latitude=>'27.60',:longitude=>'73.42',:state=>'Rajasthan'},
    {:name=>'Pali',:latitude=>'25.79',:longitude=>'73.32',:state=>'Rajasthan'},
    {:name=>'Rajsamand',:latitude=>'25.07',:longitude=>'73.88',:state=>'Rajasthan'},
    {:name=>'Ratangarh',:latitude=>'28.09',:longitude=>'74.60',:state=>'Rajasthan'},
    {:name=>'Sardarshahr',:latitude=>'28.45',:longitude=>'74.48',:state=>'Rajasthan'},
    {:name=>'Sawai Madhopur',:latitude=>'26.03',:longitude=>'76.34',:state=>'Rajasthan'},
    {:name=>'Sikar',:latitude=>'27.61',:longitude=>'75.13',:state=>'Rajasthan'},
    {:name=>'Sujangarh',:latitude=>'27.70',:longitude=>'74.46',:state=>'Rajasthan'},
    {:name=>'Suratgarh',:latitude=>'29.32',:longitude=>'73.90',:state=>'Rajasthan'},
    {:name=>'Tonk',:latitude=>'26.17',:longitude=>'75.78',:state=>'Rajasthan'},
    {:name=>'Udaipur',:latitude=>'24.58',:longitude=>'73.69',:state=>'Rajasthan'},
    {:name=>'Alandur',:latitude=>'13.03',:longitude=>'80.23',:state=>'Tamil Nadu'},
    {:name=>'Ambattur',:latitude=>'13.11',:longitude=>'80.17',:state=>'Tamil Nadu'},
    {:name=>'Ambur',:latitude=>'12.80',:longitude=>'78.72',:state=>'Tamil Nadu'},
    {:name=>'Arakonam',:latitude=>'13.08',:longitude=>'79.67',:state=>'Tamil Nadu'},
    {:name=>'Arani',:latitude=>'12.68',:longitude=>'79.28',:state=>'Tamil Nadu'},
    {:name=>'Aruppukkottai',:latitude=>'9.51',:longitude=>'78.09',:state=>'Tamil Nadu'},
    {:name=>'Attur',:latitude=>'11.60',:longitude=>'78.60',:state=>'Tamil Nadu'},
    {:name=>'Avadi',:latitude=>'13.12',:longitude=>'80.11',:state=>'Tamil Nadu'},
    {:name=>'Avaniapuram',:latitude=>'9.86',:longitude=>'78.12',:state=>'Tamil Nadu'},
    {:name=>'Bodinayakkanur',:latitude=>'10.01',:longitude=>'77.35',:state=>'Tamil Nadu'},
    {:name=>'Chengalpattu',:latitude=>'12.70',:longitude=>'79.97',:state=>'Tamil Nadu'},
    {:name=>'Dharapuram',:latitude=>'10.74',:longitude=>'77.52',:state=>'Tamil Nadu'},
    {:name=>'Dharmapuri',:latitude=>'12.13',:longitude=>'78.16',:state=>'Tamil Nadu'},
    {:name=>'Dindigul',:latitude=>'10.36',:longitude=>'77.97',:state=>'Tamil Nadu'},
    {:name=>'Erode',:latitude=>'11.35',:longitude=>'77.73',:state=>'Tamil Nadu'},
    {:name=>'Gopichettipalaiyam',:latitude=>'11.46',:longitude=>'77.43',:state=>'Tamil Nadu'},
    {:name=>'Gudalur',:latitude=>'11.76',:longitude=>'79.75',:state=>'Tamil Nadu'},
    {:name=>'Gudiyattam',:latitude=>'12.95',:longitude=>'78.86',:state=>'Tamil Nadu'},
    {:name=>'Hosur',:latitude=>'12.72',:longitude=>'77.82',:state=>'Tamil Nadu'},
    {:name=>'Idappadi',:latitude=>'11.58',:longitude=>'77.85',:state=>'Tamil Nadu'},
    {:name=>'Kadayanallur',:latitude=>'9.08',:longitude=>'77.35',:state=>'Tamil Nadu'},
    {:name=>'Kambam',:latitude=>'9.74',:longitude=>'77.28',:state=>'Tamil Nadu'},
    {:name=>'Kanchipuram',:latitude=>'12.84',:longitude=>'79.70',:state=>'Tamil Nadu'},
    {:name=>'Karur',:latitude=>'10.96',:longitude=>'78.07',:state=>'Tamil Nadu'},
    {:name=>'Kavundampalaiyam',:latitude=>'11.05',:longitude=>'76.92',:state=>'Tamil Nadu'},
    {:name=>'Kovilpatti',:latitude=>'9.19',:longitude=>'77.86',:state=>'Tamil Nadu'},
    {:name=>'Koyampattur',:latitude=>'11.01',:longitude=>'76.96',:state=>'Tamil Nadu'},
    {:name=>'Krishnagiri',:latitude=>'12.54',:longitude=>'78.21',:state=>'Tamil Nadu'},
    {:name=>'Kumarapalaiyam',:latitude=>'11.44',:longitude=>'77.73',:state=>'Tamil Nadu'},
    {:name=>'Kumbakonam',:latitude=>'10.97',:longitude=>'79.38',:state=>'Tamil Nadu'},
    {:name=>'Kuniyamuthur',:latitude=>'10.98',:longitude=>'76.95',:state=>'Tamil Nadu'},
    {:name=>'Kurichi',:latitude=>'10.92',:longitude=>'76.96',:state=>'Tamil Nadu'},
    {:name=>'Madhavaram',:latitude=>'13.02',:longitude=>'80.26',:state=>'Tamil Nadu'},
    {:name=>'Madras',:latitude=>'13.09',:longitude=>'80.27',:state=>'Tamil Nadu'},
    {:name=>'Madurai',:latitude=>'9.92',:longitude=>'78.12',:state=>'Tamil Nadu'},
    {:name=>'Maduravoyal',:latitude=>'',:longitude=>'',:state=>'Tamil Nadu'},
    {:name=>'Mannargudi',:latitude=>'10.67',:longitude=>'79.45',:state=>'Tamil Nadu'},
    {:name=>'Mayiladuthurai',:latitude=>'11.11',:longitude=>'79.65',:state=>'Tamil Nadu'},
    {:name=>'Mettupalayam',:latitude=>'11.30',:longitude=>'76.94',:state=>'Tamil Nadu'},
    {:name=>'Mettur',:latitude=>'11.80',:longitude=>'77.80',:state=>'Tamil Nadu'},
    {:name=>'Nagapattinam',:latitude=>'10.80',:longitude=>'79.84',:state=>'Tamil Nadu'},
    {:name=>'Nagercoil',:latitude=>'8.18',:longitude=>'77.43',:state=>'Tamil Nadu'},
    {:name=>'Namakkal',:latitude=>'11.23',:longitude=>'78.17',:state=>'Tamil Nadu'},
    {:name=>'Nerkunram',:latitude=>'13.04',:longitude=>'80.26',:state=>'Tamil Nadu'},
    {:name=>'Neyveli',:latitude=>'11.62',:longitude=>'79.48',:state=>'Tamil Nadu'},
    {:name=>'Pallavaram',:latitude=>'12.99',:longitude=>'80.16',:state=>'Tamil Nadu'},
    {:name=>'Pammal',:latitude=>'12.97',:longitude=>'80.11',:state=>'Tamil Nadu'},
    {:name=>'Pannuratti',:latitude=>'11.78',:longitude=>'79.55',:state=>'Tamil Nadu'},
    {:name=>'Paramakkudi',:latitude=>'9.54',:longitude=>'78.59',:state=>'Tamil Nadu'},
    {:name=>'Pattukkottai',:latitude=>'10.43',:longitude=>'79.31',:state=>'Tamil Nadu'},
    {:name=>'Pollachi',:latitude=>'10.67',:longitude=>'77.00',:state=>'Tamil Nadu'},
    {:name=>'Pudukkottai',:latitude=>'10.39',:longitude=>'78.82',:state=>'Tamil Nadu'},
    {:name=>'Puliyankudi',:latitude=>'9.18',:longitude=>'77.40',:state=>'Tamil Nadu'},
    {:name=>'Punamalli',:latitude=>'13.05',:longitude=>'80.11',:state=>'Tamil Nadu'},
    {:name=>'Rajapalaiyam',:latitude=>'9.46',:longitude=>'77.55',:state=>'Tamil Nadu'},
    {:name=>'Ramanathapuram',:latitude=>'9.37',:longitude=>'78.83',:state=>'Tamil Nadu'},
    {:name=>'Salem',:latitude=>'11.67',:longitude=>'78.16',:state=>'Tamil Nadu'},
    {:name=>'Sankarankoil',:latitude=>'9.17',:longitude=>'77.54',:state=>'Tamil Nadu'},
    {:name=>'Sivakasi',:latitude=>'9.46',:longitude=>'77.79',:state=>'Tamil Nadu'},
    {:name=>'Srivilliputtur',:latitude=>'9.52',:longitude=>'77.63',:state=>'Tamil Nadu'},
    {:name=>'Tambaram',:latitude=>'12.93',:longitude=>'80.12',:state=>'Tamil Nadu'},
    {:name=>'Tenkasi',:latitude=>'8.96',:longitude=>'77.31',:state=>'Tamil Nadu'},
    {:name=>'Thanjavur',:latitude=>'10.79',:longitude=>'79.13',:state=>'Tamil Nadu'},
    {:name=>'Theni Allinagaram',:latitude=>'10.02',:longitude=>'77.48',:state=>'Tamil Nadu'},
    {:name=>'Thiruthangal',:latitude=>'9.48',:longitude=>'77.83',:state=>'Tamil Nadu'},
    {:name=>'Thiruvarur',:latitude=>'10.78',:longitude=>'79.64',:state=>'Tamil Nadu'},
    {:name=>'Thuthukkudi',:latitude=>'8.81',:longitude=>'78.14',:state=>'Tamil Nadu'},
    {:name=>'Tindivanam',:latitude=>'12.24',:longitude=>'79.65',:state=>'Tamil Nadu'},
    {:name=>'Tiruchchirappalli',:latitude=>'10.81',:longitude=>'78.69',:state=>'Tamil Nadu'},
    {:name=>'Tiruchengode',:latitude=>'11.38',:longitude=>'77.90',:state=>'Tamil Nadu'},
    {:name=>'Tirunelveli',:latitude=>'8.73',:longitude=>'77.69',:state=>'Tamil Nadu'},
    {:name=>'Tirupathur',:latitude=>'12.50',:longitude=>'78.57',:state=>'Tamil Nadu'},
    {:name=>'Tiruppur',:latitude=>'11.09',:longitude=>'77.35',:state=>'Tamil Nadu'},
    {:name=>'Tiruvannamalai',:latitude=>'12.24',:longitude=>'79.07',:state=>'Tamil Nadu'},
    {:name=>'Tiruvottiyur',:latitude=>'13.16',:longitude=>'80.29',:state=>'Tamil Nadu'},
    {:name=>'Udagamandalam',:latitude=>'11.42',:longitude=>'76.69',:state=>'Tamil Nadu'},
    {:name=>'Udumalaipettai',:latitude=>'10.58',:longitude=>'77.24',:state=>'Tamil Nadu'},
    {:name=>'Valparai',:latitude=>'10.38',:longitude=>'76.99',:state=>'Tamil Nadu'},
    {:name=>'Vaniyambadi',:latitude=>'12.69',:longitude=>'78.60',:state=>'Tamil Nadu'},
    {:name=>'Velampalaiyam',:latitude=>'',:longitude=>'',:state=>'Tamil Nadu'},
    {:name=>'Velluru',:latitude=>'12.92',:longitude=>'79.13',:state=>'Tamil Nadu'},
    {:name=>'Viluppuram',:latitude=>'11.95',:longitude=>'79.49',:state=>'Tamil Nadu'},
    {:name=>'Virappanchatram',:latitude=>'11.40',:longitude=>'77.70',:state=>'Tamil Nadu'},
    {:name=>'Virudhachalam',:latitude=>'11.51',:longitude=>'79.32',:state=>'Tamil Nadu'},
    {:name=>'Virudunagar',:latitude=>'9.59',:longitude=>'77.95',:state=>'Tamil Nadu'},
    {:name=>'Agartala',:latitude=>'23.84',:longitude=>'91.27',:state=>'Tripura'},
    {:name=>'Agartala MCl',:latitude=>'',:longitude=>'',:state=>'Tripura'},
    {:name=>'Badharghat',:latitude=>'',:longitude=>'',:state=>'Tripura'},
    {:name=>'Agra',:latitude=>'27.19',:longitude=>'78.01',:state=>'Uttar Pradesh'},
    {:name=>'Aligarh',:latitude=>'27.89',:longitude=>'78.06',:state=>'Uttar Pradesh'},
    {:name=>'Allahabad',:latitude=>'25.45',:longitude=>'81.84',:state=>'Uttar Pradesh'},
    {:name=>'Amethi',:latitude=>'26.168',:longitude=>'81.799',:state=>'Uttar Pradesh'},

    {:name=>'Amroha',:latitude=>'28.91',:longitude=>'78.46',:state=>'Uttar Pradesh'},
    {:name=>'Aonla',:latitude=>'28.28',:longitude=>'79.15',:state=>'Uttar Pradesh'},
    {:name=>'Auraiya',:latitude=>'26.47',:longitude=>'79.50',:state=>'Uttar Pradesh'},
    {:name=>'Ayodhya',:latitude=>'26.80',:longitude=>'82.20',:state=>'Uttar Pradesh'},
    {:name=>'Azamgarh',:latitude=>'26.07',:longitude=>'83.18',:state=>'Uttar Pradesh'},
    {:name=>'Baheri',:latitude=>'28.78',:longitude=>'79.50',:state=>'Uttar Pradesh'},
    {:name=>'Bahraich',:latitude=>'27.58',:longitude=>'81.59',:state=>'Uttar Pradesh'},
    {:name=>'Ballia',:latitude=>'25.76',:longitude=>'84.15',:state=>'Uttar Pradesh'},
    {:name=>'Balrampur',:latitude=>'27.43',:longitude=>'82.18',:state=>'Uttar Pradesh'},
    {:name=>'Banda',:latitude=>'25.48',:longitude=>'80.33',:state=>'Uttar Pradesh'},
    {:name=>'Baraut',:latitude=>'29.10',:longitude=>'77.26',:state=>'Uttar Pradesh'},
    {:name=>'Bareli',:latitude=>'28.36',:longitude=>'79.41',:state=>'Uttar Pradesh'},
    {:name=>'Basti',:latitude=>'26.80',:longitude=>'82.74',:state=>'Uttar Pradesh'},
    {:name=>'Behta Hajipur',:latitude=>'',:longitude=>'',:state=>'Uttar Pradesh'},
    {:name=>'Bela',:latitude=>'25.92',:longitude=>'81.99',:state=>'Uttar Pradesh'},
    {:name=>'Bhadohi',:latitude=>'25.40',:longitude=>'82.56',:state=>'Uttar Pradesh'},
    {:name=>'Bijnor',:latitude=>'29.38',:longitude=>'78.13',:state=>'Uttar Pradesh'},
    {:name=>'Bisalpur',:latitude=>'28.30',:longitude=>'79.80',:state=>'Uttar Pradesh'},
    {:name=>'Biswan',:latitude=>'27.50',:longitude=>'81.00',:state=>'Uttar Pradesh'},
    {:name=>'Budaun',:latitude=>'28.04',:longitude=>'79.12',:state=>'Uttar Pradesh'},
    {:name=>'Bulandshahr',:latitude=>'28.41',:longitude=>'77.85',:state=>'Uttar Pradesh'},
    {:name=>'Chandausi',:latitude=>'28.46',:longitude=>'78.78',:state=>'Uttar Pradesh'},
    {:name=>'Chandpur',:latitude=>'29.14',:longitude=>'78.27',:state=>'Uttar Pradesh'},
    {:name=>'Chhibramau',:latitude=>'27.15',:longitude=>'79.52',:state=>'Uttar Pradesh'},
    {:name=>'Chitrakut Dham',:latitude=>'25.20',:longitude=>'80.84',:state=>'Uttar Pradesh'},
    {:name=>'Dadri',:latitude=>'28.57',:longitude=>'77.55',:state=>'Uttar Pradesh'},
    {:name=>'Deoband',:latitude=>'29.70',:longitude=>'77.67',:state=>'Uttar Pradesh'},
    {:name=>'Deoria',:latitude=>'26.51',:longitude=>'83.78',:state=>'Uttar Pradesh'},
    {:name=>'Etah',:latitude=>'27.57',:longitude=>'78.64',:state=>'Uttar Pradesh'},
    {:name=>'Etawah',:latitude=>'26.78',:longitude=>'79.01',:state=>'Uttar Pradesh'},
    {:name=>'Faizabad',:latitude=>'26.78',:longitude=>'82.14',:state=>'Uttar Pradesh'},
    {:name=>'Faridpur',:latitude=>'28.22',:longitude=>'79.53',:state=>'Uttar Pradesh'},
    {:name=>'Farrukhabad',:latitude=>'27.40',:longitude=>'79.57',:state=>'Uttar Pradesh'},
    {:name=>'Fatehpur',:latitude=>'25.93',:longitude=>'80.81',:state=>'Uttar Pradesh'},
    {:name=>'Firozabad',:latitude=>'27.15',:longitude=>'78.39',:state=>'Uttar Pradesh'},
    {:name=>'Gajraula',:latitude=>'28.85',:longitude=>'78.23',:state=>'Uttar Pradesh'},
    {:name=>'Ganga Ghat',:latitude=>'26.52',:longitude=>'80.45',:state=>'Uttar Pradesh'},
    {:name=>'Gangoh',:latitude=>'29.77',:longitude=>'77.25',:state=>'Uttar Pradesh'},
    {:name=>'Ghaziabad',:latitude=>'28.66',:longitude=>'77.41',:state=>'Uttar Pradesh'},
    {:name=>'Ghazipur',:latitude=>'25.59',:longitude=>'83.59',:state=>'Uttar Pradesh'},
    {:name=>'Gola Gokarannath',:latitude=>'28.08',:longitude=>'80.47',:state=>'Uttar Pradesh'},
    {:name=>'Gonda',:latitude=>'27.14',:longitude=>'81.95',:state=>'Uttar Pradesh'},
    {:name=>'Gorakhpur',:latitude=>'26.76',:longitude=>'83.36',:state=>'Uttar Pradesh'},
    {:name=>'Hapur',:latitude=>'28.73',:longitude=>'77.77',:state=>'Uttar Pradesh'},
    {:name=>'Hardoi',:latitude=>'27.42',:longitude=>'80.12',:state=>'Uttar Pradesh'},
    {:name=>'Hasanpur',:latitude=>'28.72',:longitude=>'78.28',:state=>'Uttar Pradesh'},
    {:name=>'Hathras',:latitude=>'27.60',:longitude=>'78.04',:state=>'Uttar Pradesh'},
    {:name=>'Jahangirabad',:latitude=>'28.42',:longitude=>'78.10',:state=>'Uttar Pradesh'},
    {:name=>'Jalaun',:latitude=>'26.15',:longitude=>'79.35',:state=>'Uttar Pradesh'},
    {:name=>'Jaunpur',:latitude=>'25.76',:longitude=>'82.69',:state=>'Uttar Pradesh'},
    {:name=>'Jhansi',:latitude=>'25.45',:longitude=>'78.56',:state=>'Uttar Pradesh'},
    {:name=>'Kadi',:latitude=>'23.31',:longitude=>'72.33',:state=>'Uttar Pradesh'},
    {:name=>'Kairana',:latitude=>'29.40',:longitude=>'77.20',:state=>'Uttar Pradesh'},
    {:name=>'Kannauj',:latitude=>'27.06',:longitude=>'79.91',:state=>'Uttar Pradesh'},
    {:name=>'Kanpur',:latitude=>'26.47',:longitude=>'80.33',:state=>'Uttar Pradesh'},
    {:name=>'Kanpur Cantonment',:latitude=>'26.50',:longitude=>'80.28',:state=>'Uttar Pradesh'},
    {:name=>'Kasganj',:latitude=>'27.81',:longitude=>'78.63',:state=>'Uttar Pradesh'},
    {:name=>'Khatauli',:latitude=>'29.28',:longitude=>'77.72',:state=>'Uttar Pradesh'},
    {:name=>'Khora',:latitude=>'',:longitude=>'',:state=>'Uttar Pradesh'},
    {:name=>'Khurja',:latitude=>'28.26',:longitude=>'77.85',:state=>'Uttar Pradesh'},
    {:name=>'Kiratpur',:latitude=>'29.52',:longitude=>'78.20',:state=>'Uttar Pradesh'},
    {:name=>'Kosi Kalan',:latitude=>'27.80',:longitude=>'77.44',:state=>'Uttar Pradesh'},
    {:name=>'Laharpur',:latitude=>'27.72',:longitude=>'80.90',:state=>'Uttar Pradesh'},
    {:name=>'Lakhimpur',:latitude=>'27.95',:longitude=>'80.78',:state=>'Uttar Pradesh'},
    {:name=>'Lakhnau',:latitude=>'26.85',:longitude=>'80.92',:state=>'Uttar Pradesh'},
    {:name=>'Lakhnau Cantonment',:latitude=>'26.81',:longitude=>'80.97',:state=>'Uttar Pradesh'},
    {:name=>'Lalitpur',:latitude=>'24.70',:longitude=>'78.41',:state=>'Uttar Pradesh'},
    {:name=>'Loni',:latitude=>'28.75',:longitude=>'77.28',:state=>'Uttar Pradesh'},
    {:name=>'Mahoba',:latitude=>'25.30',:longitude=>'79.87',:state=>'Uttar Pradesh'},
    {:name=>'Mainpuri',:latitude=>'27.24',:longitude=>'79.02',:state=>'Uttar Pradesh'},
    {:name=>'Mathura',:latitude=>'27.50',:longitude=>'77.68',:state=>'Uttar Pradesh'},
    {:name=>'Mau',:latitude=>'25.96',:longitude=>'83.56',:state=>'Uttar Pradesh'},
    {:name=>'Mauranipur',:latitude=>'25.24',:longitude=>'79.13',:state=>'Uttar Pradesh'},
    {:name=>'Mawana',:latitude=>'29.11',:longitude=>'77.91',:state=>'Uttar Pradesh'},
    {:name=>'Mirat',:latitude=>'28.99',:longitude=>'77.70',:state=>'Uttar Pradesh'},
    {:name=>'Mirat Cantonment',:latitude=>'29.02',:longitude=>'77.67',:state=>'Uttar Pradesh'},
    {:name=>'Mirzapur',:latitude=>'25.16',:longitude=>'82.56',:state=>'Uttar Pradesh'},
    {:name=>'Modinagar',:latitude=>'28.92',:longitude=>'77.62',:state=>'Uttar Pradesh'},
    {:name=>'Moradabad',:latitude=>'28.84',:longitude=>'78.76',:state=>'Uttar Pradesh'},
    {:name=>'Mubarakpur',:latitude=>'26.09',:longitude=>'83.28',:state=>'Uttar Pradesh'},
    {:name=>'Mughal Sarai',:latitude=>'25.30',:longitude=>'83.12',:state=>'Uttar Pradesh'},
    {:name=>'Muradnagar',:latitude=>'28.78',:longitude=>'77.50',:state=>'Uttar Pradesh'},
    {:name=>'Muzaffarnagar',:latitude=>'29.48',:longitude=>'77.69',:state=>'Uttar Pradesh'},
    {:name=>'Nagina',:latitude=>'29.45',:longitude=>'78.43',:state=>'Uttar Pradesh'},
    {:name=>'Najibabad',:latitude=>'29.62',:longitude=>'78.33',:state=>'Uttar Pradesh'},
    {:name=>'Nawabganj',:latitude=>'26.94',:longitude=>'81.19',:state=>'Uttar Pradesh'},
    {:name=>'Noida',:latitude=>'28.58',:longitude=>'77.33',:state=>'Uttar Pradesh'},
    {:name=>'Obra',:latitude=>'24.42',:longitude=>'82.98',:state=>'Uttar Pradesh'},
    {:name=>'Orai',:latitude=>'25.99',:longitude=>'79.45',:state=>'Uttar Pradesh'},
    {:name=>'Pilibhit',:latitude=>'28.64',:longitude=>'79.81',:state=>'Uttar Pradesh'},
    {:name=>'Pilkhuwa',:latitude=>'28.72',:longitude=>'77.65',:state=>'Uttar Pradesh'},
    {:name=>'Rae Bareli',:latitude=>'26.23',:longitude=>'81.23',:state=>'Uttar Pradesh'},
    {:name=>'Ramgarh Nagla Kothi',:latitude=>'',:longitude=>'',:state=>'Uttar Pradesh'},
    {:name=>'Rampur',:latitude=>'28.82',:longitude=>'79.02',:state=>'Uttar Pradesh'},
    {:name=>'Rath',:latitude=>'25.58',:longitude=>'79.57',:state=>'Uttar Pradesh'},
    {:name=>'Renukut',:latitude=>'24.20',:longitude=>'83.03',:state=>'Uttar Pradesh'},
    {:name=>'Saharanpur',:latitude=>'29.97',:longitude=>'77.54',:state=>'Uttar Pradesh'},
    {:name=>'Sahaswan',:latitude=>'28.08',:longitude=>'78.74',:state=>'Uttar Pradesh'},
    {:name=>'Sambhal',:latitude=>'28.59',:longitude=>'78.56',:state=>'Uttar Pradesh'},
    {:name=>'Sandila',:latitude=>'27.08',:longitude=>'80.52',:state=>'Uttar Pradesh'},
    {:name=>'Shahabad',:latitude=>'27.65',:longitude=>'79.95',:state=>'Uttar Pradesh'},
    {:name=>'Shahjahanpur',:latitude=>'27.88',:longitude=>'79.90',:state=>'Uttar Pradesh'},
    {:name=>'Shamli',:latitude=>'29.46',:longitude=>'77.31',:state=>'Uttar Pradesh'},
    {:name=>'Sherkot',:latitude=>'29.35',:longitude=>'78.58',:state=>'Uttar Pradesh'},
    {:name=>'Shikohabad',:latitude=>'27.12',:longitude=>'78.58',:state=>'Uttar Pradesh'},
    {:name=>'Sikandarabad',:latitude=>'28.44',:longitude=>'77.69',:state=>'Uttar Pradesh'},
    {:name=>'Sitapur',:latitude=>'27.57',:longitude=>'80.69',:state=>'Uttar Pradesh'},
    {:name=>'Sukhmalpur Nizamabad',:latitude=>'',:longitude=>'',:state=>'Uttar Pradesh'},
    {:name=>'Sultanpur',:latitude=>'26.26',:longitude=>'82.06',:state=>'Uttar Pradesh'},
    {:name=>'Tanda',:latitude=>'26.55',:longitude=>'82.65',:state=>'Uttar Pradesh'},
    {:name=>'Tilhar',:latitude=>'27.98',:longitude=>'79.73',:state=>'Uttar Pradesh'},
    {:name=>'Tundla',:latitude=>'27.20',:longitude=>'78.28',:state=>'Uttar Pradesh'},
    {:name=>'Ujhani',:latitude=>'28.02',:longitude=>'79.02',:state=>'Uttar Pradesh'},
    {:name=>'Unnao',:latitude=>'26.55',:longitude=>'80.49',:state=>'Uttar Pradesh'},
    {:name=>'Varanasi',:latitude=>'25.32',:longitude=>'83.01',:state=>'Uttar Pradesh'},
    {:name=>'Vrindavan',:latitude=>'27.58',:longitude=>'77.70',:state=>'Uttar Pradesh'},
    {:name=>'Dehra Dun',:latitude=>'30.34',:longitude=>'78.05',:state=>'Uttaranchal'},
    {:name=>'Dehra Dun Cantonment',:latitude=>'30.34',:longitude=>'77.97',:state=>'Uttaranchal'},
    {:name=>'Gola Range',:latitude=>'',:longitude=>'',:state=>'Uttaranchal'},
    {:name=>'Haldwani',:latitude=>'29.23',:longitude=>'79.52',:state=>'Uttaranchal'},
    {:name=>'Haridwar',:latitude=>'29.98',:longitude=>'78.16',:state=>'Uttaranchal'},
    {:name=>'Kashipur',:latitude=>'29.22',:longitude=>'78.96',:state=>'Uttaranchal'},
    {:name=>'Pithoragarh',:latitude=>'29.58',:longitude=>'80.22',:state=>'Uttaranchal'},
    {:name=>'Rishikesh',:latitude=>'30.12',:longitude=>'78.29',:state=>'Uttaranchal'},
    {:name=>'Rudrapur',:latitude=>'',:longitude=>'',:state=>'Uttaranchal'},
    {:name=>'Rurki',:latitude=>'29.87',:longitude=>'77.89',:state=>'Uttaranchal'}
    ]
  )
  end
end
